### ISSUE TITLE
OSMC is Kodi

### ISSUE THREAD

**Issue by g4rret** [tycrek/degoogle#10]
>    - Kodi - It's incredibly powerful. Backed by one of the strongest communities around. Tons of plugins to do nearly anything you want.
>    - OSMC - Free, open source media center. Strongest competitor to Kodi.

OSMC can't be a competitor to Kodi - OSMC is a Linux distro with Kodi pre-installed.

**Comment by lgiard** [comment]
To add on that : Kodi is an open source Media center software that you can install on any platform (windows, linux, android, raspberry pi,...). I would put it in the category "Play Music & Play Movies and TV". 
There are other alternative to OSMC like LibrELEC which is another linux distro with Kodi pre-installed. Both have advantages (especially as they are optimised for media center purpose) so i suppose they could be both listed ? :-)

**Comment by tycrek** [comment]
@g4rret @lgiard Thank you, I will update the guide to account for this!
