### ISSUE TITLE
[OTHER] Mobile Application :  Blokada

### ISSUE THREAD

**Issue by ghost** [tycrek/degoogle#102]
"Blokada" creates a tunnel to block telemetry and ads among all the applications on Android. 

The app allows a granular control of the connections made by Android apps in comparison with other apps that do not show anything to the end-user. 

Available on F-droid and Google Play but the versions are different on both platforms. Google deems "illegal" some functions of "Blokada" since it can block Google's data harvesting completely (it can block any connection to Google domains if users want it).

It is recommended to install Blokada from F-droid.

https://blokada.org

**Comment by danarel** [comment]
This is a good recommendation.

**Comment by tycrek** [comment]
For now I'll have to create a new subsection "Other" since I don't really have a spot for this to go, as it's not an alternative. Really good suggestion though, and nice that it's on F-Droid.
