### ISSUE TITLE
Nextcloud is not 5 eyes

### ISSUE THREAD

**Issue by danarel** [tycrek/degoogle#105]
On the list, Nextcloud is listed as 5eyes, but, it's worth noting that Nextcloud does not offer it's own hosting services. If you don't want to self-host, you have to pick your own operator that sells the Nextcloud service.

So I think it can be misleading to call them 5-eyes since they only offer the code, not the storage, making their physical location meaningless.

I believe the same applies to owncloud as well, but I have not checked in a long time to see if they offer hosting of their own.

**Comment by tycrek** [comment]
Not sure where you're seeing 5-eyes, I'm only seeing it listed as 14-eyes on line 165. I'll remove the 14-eyes note however and I'll do the same for ownCloud.
