### ISSUE TITLE
Contibuting Recommendation

### ISSUE THREAD

**Issue by danarel** [tycrek/degoogle#108]
Can I make a recommendation that it be part of the request process that all Pull Requests have an issue opened first?

That way the discussion about the recommendation can happen?

Just a suggestion.

**Comment by tycrek** [comment]
We could do this, I like that idea. I'll add that into the contributing guidelines. I won't make it a strict requirement for opening a PR, but it will be recommended to open an Issue first.

**Comment by tycrek** [comment]
@danarel Updated [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md) in that commit, let me know if you have a better way to word it.
