### ISSUE TITLE
[FIX] Keybase acquired by Zoom, Inc.

### ISSUE THREAD

**Issue by multimob** [tycrek/degoogle#111]
**Service name**: Keybase

**Error**: In May 2020, Zoom reported acquiring Keybase (https://keybase.io/blog/keybase-joins-zoom) with plans to integrate both services (https://blog.zoom.us/wordpress/2020/05/07/zoom-acquires-keybase-and-announces-goal-of-developing-the-most-broadly-used-enterprise-end-to-end-encryption-offering/).  Zoom, Inc. has an awfully bad record about privacy.  I doubt whether we should continue recommending it.

**Proposed changes**: Maybe a notice in the description + we should re-assess the situation in a couple of weeks/months to see whether their TOS have worsened.

**Comment by tycrek** [comment]
I didn't know this happened, thank you for bringing it up. I agree, later on we should re-asses.
