### ISSUE TITLE
[OTHER] User privacy from Joomla video?

### ISSUE THREAD

**Issue by danjde** [tycrek/degoogle#114]
Hi tycrek!
First, relax, this is not an issue ;-)

Second: do you know if exist for Joomla a way to publish youtube video, bypassing the information collection by Google?
I know invidio.us, but how embed a video from invidio.us into Joomla? Rather a Joomla plugin would be needed that redirects the user's IP.

Mah is a question a bit like that, maybe would be more appropriate to ask in the appropriate forum ..is that the privacy question is little heard in general.

Anyway, I'm part of an association that is working and informing on this criticality --> 3x1t.org

Ciao!

Davide

**Comment by tycrek** [comment]
Unfortunately it [doesn't look like you can embed Invidous](https://jsfiddle.net/3Lzc7syn/) (I tested with a random LTT video).

And yes, it would be more helpful to you to try asking in the [official forum](https://forum.joomla.org/). I haven't used Joomla myself.
