### ISSUE TITLE
[REMOVE] Remove AdNauseam

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#117]
**Service name**: AdNauseam

**Reason**: While it has good intentions, even if you’re polluting tracking data, the ad network still gets information about you and your browsing habits. Furthermore, its fundamental flaw is that by using it you are supporting the advertising companies. Clicking on the ads generates revenue for these companies. Seeing as it is a fork of uBlock Origin and doesn't improve on it, it should be removed.

**Comment by tycrek** [comment]
I agree. Not sure how they much more obfuscation it does since it does still access the ad server in a way, where uBlock completely blocks it from connecting at all.
