### ISSUE TITLE
[OTHER] Switch to Markdown tables & automated builds

### ISSUE THREAD

**Issue by tycrek** [tycrek/degoogle#118]
I'm experimenting with a potentially better layout than the current list-based layout. I added a test to [the grid branch](https://github.com/tycrek/degoogle/tree/grid#web-based-products) that shows how it might look. Personally I think it looks great.

The downside is that editing the code would be a lot more of a hassle, at least visually. I have considered for a long time creating an automated build process:

1. Put all the data in a separate YAML file. Pull requests will have to edit this file instead of directly editing the README.
2. Once a PR is merged, the build process will automatically generate the README file with the grids and all other data.
3. The GitHub Pages on [my personal domain](https://degoogle.jmoore.dev/) automatically updates, as does the `master` branch README.
4. It's unlikely to happen but automating updating the r/privacy wiki would be nice.

I've held off on this as I don't know how complicated it would be. I'll try some things out and update this issue as necessary.

**Comment by tycrek** [comment]
This might potentially remove the need to do anything with #113.

Another idea I just had: the build process could scan all the issues/pull requests and add any missing names to CONTRIBUTORS.md

**Comment by danarel** [comment]
I like the table layout!

**Comment by tycrek** [comment]
Thanks! It definitely looks a lot cleaner.

As for the build process, I might try it with Node.js and [this workflow template](https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions) for GitHub Actions. I've been doing Node.js for work and personal projects for a little over a year now so it shouldn't be too hard.

**Comment by tycrek** [comment]
Looks like I can also [edit the wiki through the Reddit API](https://old.reddit.com/dev/api#POST_api_wiki_edit). Dealing with keeping API keys private might be a challenge but should be possible [through Secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets). However if other contributors have access to these, I might need to discuss this with the r/privacy moderators first.

**Comment by tycrek** [comment]
Builds are now automated and all alternatives are in table format.
