### ISSUE TITLE
startpage is not a privacy search engine

### ISSUE THREAD

**Issue by pydo** [tycrek/degoogle#12]
Startpage was recently acquired by an adtech company.
Please consider removing it from your list of google search alternatives.

https://reclaimthenet.org/startpage-buyout-ad-tech-company/
https://www.startpage.com/blog/company-updates/startpage-and-privacy-one-group/

**Comment by ThijsRay** [comment]
There haven't been any changes in their privacy policy. The fact that their majority stakeholder changed doesn't mean that Startpage is suddenly not a privacy search engine anymore. It is reasonable to have concerns, but they have addressed those [here](https://support.startpage.com/index.php?/Knowledgebase/Article/View/1275/0/what-is-startpages-relationship-with-privacy-onesystem1-and-what-does-this-mean-for-my-privacy-protections) in my opinion.

**Comment by DatAres37** [comment]
^ this and I'd rather remove ecosia, because personalized search results are enabled by default afaics.

**Comment by tycrek** [comment]
@pydo @ThijsRay You both make good points. I'll update the guide with a reference to this issue.

@DatAres37 I agree. It will be removed in the next update.
