### ISSUE TITLE
[OTHER] Android App : "TrackerControl"

### ISSUE THREAD

**Issue by E5dZEUpc3BKaJrHnQVZd5zE** [tycrek/degoogle#121]
"TrackerControl allows users to monitor and control the widespread, ongoing, hidden data collection in mobile apps about user behaviour ('tracking')".

Only available on **F-droid**. Similar functionality to "Blokada" (already listed)

https://github.com/OxfordHCC/tracker-control-android

**Comment by tycrek** [comment]
Looks good, thanks!
