### ISSUE TITLE
[NEW] New Fonts Alternative: Brick.im

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#123]
**Service name**: Brick.im

**Service URL**: [Brick.im](https://brick.im/)

**5/9/14 eyes?**: unknown

**Description**: Open source fonts that work in a very similar way to Google fonts.

**Comment by tycrek** [comment]
Added, thanks!

**Comment by fv0** [comment]
Most fonts are down and return a 503. Is this project abandoned? Is there an alternative?
