### ISSUE TITLE
[NEW] New photos alternative: crypt.ee

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#125]
**Service name**: crypt.ee

**Service URL**:  [crypt.ee](https://crypt.ee/)

**5/9/14 eyes?**: Estonia (Key disclosure laws may apply, not in the 'eyes')

**Description**: Encrypted photo storage in a simple solution similar to Google Photos.

**Comment by tycrek** [comment]
I remember seeing these guys last year, but their photos hadn't been fully rolled out. Glad to see they have a full service now, I'll add them in!
