### ISSUE TITLE
[NEW] New GMail alternative: Thexyz

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#128]
**Service name**: Thexyz

**Service URL**: [thexyz.com](https://www.thexyz.com/)

**5/9/14 eyes?**: Canada (5 eyes, key disclosure laws apply)

**Description**: Thexyz is a Canadian company offering privacy-conscious business email. Premium webmail costs $2.95/m.

**Comment by tycrek** [comment]
This looks great, I especially love their [privacy and security page](https://www.thexyz.com/about/privacy-and-security). I'll add it in right away.
