### ISSUE TITLE
[NEW] Atom? 

### ISSUE THREAD

**Issue by woutfeys** [tycrek/degoogle#132]
**Service name**: *Atom*

**Service URL**: *https://atom.io/*

**5/9/14 eyes?**: yes/no/**unknown**

**Description**: *Atom is a coding editor that 1. Is Open-source and 2. Is free!*

**Comment by FreddyMarsden** [comment]
Google isn't really offering an alternative to Atom. Not sure if it would fit.

Equally, Atom was made by GitHub. Github is now owned Microsoft.  Who knows how is that going to impact further development?

**Comment by tycrek** [comment]
If it were to be added it would fit in with Vim and Emacs in [Android Studio](https://degoogle.jmoore.dev/#android-studio-not-specifically-for-android-development-just-in-general). As of right now it is using the MIT open source license. I'm in favour of adding it as long as users are able to clone the [repo](https://github.com/atom/atom) and build it themselves. Once this isn't possible and the only way to run it is through Microsoft binaries, then there is cause for concern.

**Comment by woutfeys** [comment]
Yes indeed, so should we add it and if Microsoft tries to push it under their own wings we remove it? sounds like a great plan. And my idea was as an alternative to Android Studio.
