### ISSUE TITLE
[NEW] New  News alternative: Miniflux

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#133]
**Service name**: Miniflux

**Service URL**: [Miniflux.app](https://miniflux.app/)

**5/9/14 eyes?**: unknown (although the developer appears to be french)

**Description**: Miniflux is a minimalist and opinionated feed reader. Completely open source, along with automatically removing pixel trackers.

**Comment by tycrek** [comment]
Looks like it's self hosted, perhaps eyes can be `null`?

**Comment by FreddyMarsden** [comment]
Ah yes, probably should have mentioned. However they do offer there own hosting plans for only $15/year.
