### ISSUE TITLE
[FIX] Fix/update alternative for many Apps

### ISSUE THREAD

**Issue by Glitchy-Tozier** [tycrek/degoogle#134]
**Add Launcher: KISS Launcher**: *Fast and small Launcher, mainly relies on an app-search-bar, which makes it very easy to open up apps quickly. (Open Source, of course) https://kisslauncher.com/*

**Add SMS/MMS-App: Signal**: "Signal possesses SMS/MMS capabilities. Using it as your default SMS-app has the advantage of having your SMS and your online-messaging-service integrated within one app.*

**Proposed changes**: **Silence* hasn't been updated for a long time. The same thing applies to *kboard*... Maybe they're no longer active?*

**Additional details**: **Open Camera* can be downloaded from F-Droid. The same thing applies to the following:*
- All "Simple-" apps. (Simple Alarm Clock for example)
- Silence
- Hacker's Keyboard
- kboard (I think)
- OpenBoard
- Standard Notes ("S. Notes")
- RiotX
- Conversations
- Probably a few others that I didn't check.

**Comment by tycrek** [comment]
For Silence, the [master branch](https://git.silence.dev/Silence/Silence-Android/-/tree/master) was [updated 5 days ago](https://git.silence.dev/Silence/Silence-Android/-/commit/4e96f3fb2128d3fd3d840d38685b34c54ac53d6e). Granted it was a translation, but it at least shows someone is maintaining the repo. The [unstable branch](https://git.silence.dev/Silence/Silence-Android/-/tree/unstable) is slightly older at [one month ago](https://git.silence.dev/Silence/Silence-Android/-/commit/764d07e718d653ef6c482a3758d98488627da157). Development of new features might be slow, but I wouldn't go as far as saying it isn't active yet.

As for KBoard, the last commit was [over a year ago](https://github.com/adgad/kboard/commit/30f7423fc43e4ae90e0bdd5008015d216f5e8687) so I think it's safe to say it might be abandoned. To try and confirm this I opened [an Issue](https://github.com/adgad/kboard/issues/16) in the repo.

Thanks for the fixes and for finding all the F-Droid apps!

**Comment by tycrek** [comment]
F-Droid fixes:

- Open Camera: **fixed**
- All "Simple-" apps. (Simple Alarm Clock for example)
- Silence: **already had F-Droid linked, package `org.smssecure.smssecure` ([link](https://f-droid.org/en/packages/org.smssecure.smssecure/))**
- Hacker's Keyboard: **fixed**
- kboard: **fixed**
- OpenBoard: **fixed**
- Standard Notes ("S. Notes"): **fixed** (in Web-based)
- RiotX: **half fixed**. for Riot I moved the existing app ([Riot.im](https://f-droid.org/packages/im.vector.alpha/)) from where it was in Web-Based to Hangouts in Mobile Apps. Would you suggest we put Riot.im, RiotX, or both?
- Conversations: **fixed**

Thanks again for finding these

**Comment by tycrek** [comment]
Closing for now, if anyone has suggestions on what to do with Silence feel free to leave a comment and I can re-open.
