### ISSUE TITLE
[NEW] Alternative to firebase - Supabase

### ISSUE THREAD

**Issue by woutfeys** [tycrek/degoogle#135]
**Service name**: *Supabase*

**Service URL**: *https://github.com/supabase*

**5/9/14 eyes?**: yes/no/**unknown**

**Description**: *Supabase is an opensource alternative to Firebase, I'm not sure if you can self-host it so they may keep some code private which is a red flag but I still wanted to share it.*

**Comment by tycrek** [comment]
Looks promising, just getting clarification in their repo about server location and self-hosting.

**Comment by tycrek** [comment]
[Response from a contributor](https://github.com/supabase/supabase/issues/85#issuecomment-636010946). I'll add it with `null` eyes for now, might need to be updated in the future.
