### ISSUE TITLE
[OTHER] Calculator++ (Available on F-droid)

### ISSUE THREAD

**Issue by ghost** [tycrek/degoogle#149]
A calculator with scientific functions recently added to F-droid. 

It provides more functions than the "Simple Calculator" already listed.

https://f-droid.org/en/packages/org.solovyev.android.calculator/

**Comment by woutfeys** [comment]
seems kinda neat! is it open-source?

**Comment by tycrek** [comment]
> seems kinda neat! is it open-source?

[Source code](https://github.com/Bubu/android-calculatorpp) link grabbed from F-Droid page

**Comment by tycrek** [comment]
Also, I will add this when I have time later today :)

**Comment by woutfeys** [comment]
Great!
