### ISSUE TITLE
[FIX] Fix/update alternative

### ISSUE THREAD

**Issue by shorca** [tycrek/degoogle#150]
**Service name**: *Protonmail*

**Error**: *Android App uses Google Cloud Service to deliver Notification*

**Proposed changes**: *Add the info to the entry*

**Additional details**: *found in Protonmail's feature request page like [this](https://protonmail.uservoice.com/forums/284483-feedback?status_id=1468599&query=google)*

**Comment by tycrek** [comment]
The only relevant thread from that link is [this one posted in August 2016](https://protonmail.uservoice.com/forums/284483-feedback/suggestions/15495990-can-you-please-release-an-downloadable-apk-version). Someone in the comments links to [this one](https://protonmail.uservoice.com/forums/284483-feedback/suggestions/11359776-publish-android-app-to-f-droid-and-remove-reliance). What are your thoughts? The entry already states:

> Can be downloaded from the Play Store, but may work with one of the store replacements above (such as Yalp).

I know this is a pretty bad description, how would you suggest we improve it?

**Comment by shorca** [comment]
I tried Yalp but it seems not working anymore due to lack of maintenance.  How about we replace Yalp with Aurora Store, which I tried but the app still doesn't deliver notification. I don't know where to put this information on the web, so I suggest adding this here, like "notification doesn't work without Google Play Store"

**Comment by tycrek** [comment]
Threads about captcha from feedback forum:

- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/17638123-captcha-without-google
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/40059430-do-not-use-google-recaptcha
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/40549459-do-not-use-google-s-recaptcha

Other Google related threads:

- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/37251394-making-the-app-availeble-for-non-google-users
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/10401618-stop-using-google-fonts-which-track-users-browsi
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/38175727-privacy-with-google
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/19635550-remove-dependance-on-google-play-services
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/39692812-keep-google-from-accessing
- https://protonmail.uservoice.com/forums/284483-feedback/suggestions/11614899-protonmail-should-be-google-free

**Comment by tycrek** [comment]
No response, closing
