### ISSUE TITLE
[NEW] New Blogger/Sites alternative

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#151]
**Service name**: Bear

**Service URL**: [bearblog.dev](https://bearblog.dev/)

**5/9/14 eyes?**: unknown

**Description**: Free, no-nonsense, super-fast blogging. No javascript, no stylesheets, no trackers. Just your words.

**Comment by tycrek** [comment]
Looks great, love the no-nonsense ideology.

Unrelated but I'm glad to see the bot is working with labelling!

**Comment by tycrek** [comment]
@FreddyMarsden would you be opposed to using 5-eyes for this? Looks like the site server is in the USA, but also appears that you can self-host.
