### ISSUE TITLE
[REMOVE] Remove alternative: CodeFund

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#164]
Sadly, CodeFund is [shutting down](https://codefund.io/) and should no longer be listed.

### Checklist

- [ ] **I am affiliated with this alternative**
- [X] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

Unfortunately there is no real alternative at the moment.

**Comment by tycrek** [comment]
Well shoot, that sucks :( best of luck to the CodeFund team. I'll get this removed from this list.
