### ISSUE TITLE
Maps section

### ISSUE THREAD

**Issue by mahdi1234** [tycrek/degoogle#166]
Mapillary was recently acquired by Facebook definitely worth mentioning.

Other than that I suggest maybe split/ad info on car navigation vs tracking as there's many great apps and it none is listed.

https://play.google.com/store/apps/details?id=com.generalmagic.magicearth for car

and

https://f-droid.org/en/packages/net.osmand.plus/ for hiking

for example, so far it lists only web solutions.

**Comment by tycrek** [comment]
> Mapillary was recently acquired by Facebook definitely worth mentioning.

Added a note with a link to the [blog post](https://blog.mapillary.com/news/2020/06/18/Mapillary-joins-Facebook.html)

> https://play.google.com/store/apps/details?id=com.generalmagic.magicearth

This is a strong alternative, however the guide is planning on moving to only open-source services. I am aware there are already services in the guide that are closed-source; these will eventually be removing once we get around to them.

> https://f-droid.org/en/packages/net.osmand.plus/ for hiking

OsmAnd is already listed in the mobile maps section but is missing a link to that F-Droid repo.

> for example, so far it lists only web solutions.

There is a section "Maps/Waze" in Mobile Apps category.

**Comment by tycrek** [comment]
Oops, meant to close in #171
