### ISSUE TITLE
[NEW] New alternative

### ISSUE THREAD

**Issue by akfaew** [tycrek/degoogle#167]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [x] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: Syften
  - **Alternative URL**: https://syften.com
  - **5/9/14 eyes**: unknown
  - **Description**: Alternative to Google Alerts
- **FLOSS**
  - Price: paid
  - Self-host: no
- **Encryption**
  - HTTPS: yes
- **Transparency**
  - Public ownership: no
  - 3rd-party audits: no
- **Privacy**
  - Anonymous payments: no
  - Analytics: Google Analytics
  - Captcha: no

**Comment by tycrek** [comment]
On the fence about it using Google Analytics and storing data in Google Cloud.

**Comment by SuperSandro2000** [comment]
It is not a real privacy alternative if google still gets the data.
