### ISSUE TITLE
[NEW] New AdSense alternative: 

### ISSUE THREAD

**Issue by FreddyMarsden** [tycrek/degoogle#182]
### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: Ethical Ads
  - **Alternative URL**: [ethicalads.io](https://www.ethicalads.io/index.html)
  - **5/9/14 eyes**: unknown
  - **Description**: a  developer-focused, privacy-obsessed ad network from the fine folks at Read the Docs
- **FLOSS**
  - Repository: [here](https://github.com/readthedocs/ethical-ad-server)
  - Active: yes
  - Download: no
  - Price: entirely depends on wether you are a publisher or advertiser.
  - Self-host: no.
- **Encryption**
  - HTTPS: yes
  - E2EE: N/A
  - Modern Encryption: N/A
- **Transparency**
  - Public ownership: [yes](https://readthedocs.org/)
  - 3rd-party audits: unsure
- **Privacy**
  - Anonymous payments: ?
  - Analytics: none!
  - Captcha: unsure
- **Extras**
  - .onion address: none
  - Warrant canary: unsure

**Comment by tycrek** [comment]
This is awesome, thank you!

Your username is already listed in the contributors file. Let me know if you would like it removed

**Comment by FreddyMarsden** [comment]
@tycrek please include me in the list, but I'd prefer not to be thanked in the actual document. Thanks!

**Comment by tycrek** [comment]
Sounds good, I'll remove you from the Yaml :)

**Comment by tycrek** [comment]
Pushed directly to `master` in commit https://github.com/tycrek/degoogle/commit/9b953e105f2829508a0d21208f0f552d2fc287a5
