### ISSUE TITLE
[REMOVE] Remove alternative

### ISSUE THREAD

**Issue by resynth1943** [tycrek/degoogle#186]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [X] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [X] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **Alternative name**: Cloudflare
- **Reason**: You should not recommend Cloudflare. 

- [They are openly hostile against free-speech](https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README_en.md).
- [Oppressed minorities under threat (who then use Tor) are constantly challenged by Cloudflare's 'checks](https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README_en.md)
- They submit personal details of people who report a website. 8chan once submitted the personal details of someone who reported their website to Cloudflare.
- [They intercept any and all SSL / TLS traffic to websites, allowing them to see raw personal information of people who probably aren't even aware they are being tracked by Cloudflare](https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README_en.md)
- [Legitimate bots and crawlers are actively blocked by Cloudflare.](https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README_en.md)
- [Cloudflare's uptime is not 100%](http://qntra.net/2019/07/usg-surveillance-firm-cloudflare-brings-downtime-to-many-popular-websites/)
- [Legitimate bots and crawlers are banned by Cloudflare's 'protection'](https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README_en.md)
- [The check requires JavaScript and cookies to be enabled, it is horrendous for privacy and security](https://codeberg.org/crimeflare/cloudflare-tor/src/branch/master/README_en.md)

There are many more reasons in the website I repeatedly link. I would encourage you to read more on Cloudflare.

By recommending Cloudflare, you are promoting the above abuse of the 'open web', which Cloudflare actively diminishes any prospect of. I am disappointed this trusted resource recommends Cloudflare, when they currently hold a strangehold on free speech, privacy and security.

**Comment by resynth1943** [comment]
Thank you so much :blush:

**Comment by tycrek** [comment]
No problem, thank you for providing those resources!
