### ISSUE TITLE
[NEW] New alternative (PhotoStructure for Google Photos)

### ISSUE THREAD

**Issue by mceachen** [tycrek/degoogle#190]
### Checklist

- [x] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [x] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: { PhotoStructure }
  - **Alternative URL**: { https://photostructure.com }
  - **5/9/14 eyes**: { yes }
  - **Description**: { PhotoStructure is a self-hosted web-based digital asset manager that scales to millions of files and runs on macOS, Windows, Linux, and Docker. Library directories are portable across platforms and hosts. Robust photo and video deduplication handles both exact and "fuzzy" matches based on metadata and image contents. The mobile-friendly web UI is performant even when served on low-powered, low-RAM servers, and viewed on older hardware. }
- **FLOSS**
  - Repository: https://github.com/photostructure/photostructure-for-servers (not OSS: obfuscated source)
  - Active: yes
  - Download: https://photostructure.com/
  - Price: freemium
  - Self-host: only
- **Encryption**
  - HTTPS: no (requires external reverse proxy)
  - E2EE: no (requires external reverse proxy)
  - Modern Encryption: no (requires external reverse proxy)
- **Transparency**
  - Public ownership: yes [PhotoStructure, Inc.](https://photostructure.com)
  - 3rd-party audits: no
- **Privacy**
  - Anonymous payments: no
  - Analytics: no (but error reports are opt-out)
  - Captcha: no

**Comment by tycrek** [comment]
Added per https://github.com/tycrek/degoogle/issues/217 because I saw it before this issue
