### ISSUE TITLE
[NEW] New alternative

### ISSUE THREAD

**Issue by owlguy** [tycrek/degoogle#196]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [x] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Brave Browser**: { Alternative name here. Required }
  - **https://github.com/brave/brave-browser**: { Alternative URL here. Required }
  - **yes**: { yes/no/unknown }
  - **Brave is the market leader for producing a Google-cleansed chromium fork.**: { detail why this alternative should be added }
- **FLOSS**
  - Repository: { https://github.com/brave/brave-browser }
  - Active: { yes} (any branch in source repo active within past four months, excluding translations)
  - Download: { Direct } (Direct is direct downloads, such as GitHub releases)
  - Price: { free } (free: no payments at all; paid: no free tier excluding trials; freemium: any mix of free tier and paid plans)
  - Self-host: { no } (use "only" if the only option is self hosting; for example, LibreOffice Online)
- **Encryption**
  - HTTPS: { yes }
  - E2EE: { no }
  - Modern Encryption: { yes }
- **Transparency**
  - Public ownership: { no } [Parent company name](https://brave.com/about/)
  - 3rd-party audits: { no } [Link to audit history](https://audit.history.url)
- **Privacy**
  - Anonymous payments: { yes/no } (these types of payments can include cash, cryptocurrency, gift cards)
  - Analytics: { yes/no } { type of analytics }
  - Captcha: { recaptcha/hcaptcha/other }
- **Extras**
  - .onion address: { .onion address }
  - Warrant canary: { yes/no } [Link to canary](https://warrant.canary.url)

**Comment by tycrek** [comment]
#69
