### ISSUE TITLE
Clarify what "n-eyes" means

### ISSUE THREAD

**Issue by fabiancook** [tycrek/degoogle#2]
It is not obvious as to what the implications of using the services marked with these labels actually means.

> 5-eyes, 9-eyes, and 14-eyes services will be listed, and marked as such. This means the company, not the server IP.
> 5: Australia, Canada, New Zealand, UK, USA
> 9: Denmark, France, Netherlands, Norway
> 14: Germany, Belgium, Italy, Sweden, Spain

**Comment by tycrek** [comment]
Added link from Useful Links in this section as well. Thanks for the tip, makes more sense to have it hear.

commit [534888d](https://github.com/tycrek/degoogle/commit/534888dcceb389a95485e700db7dbd679b9f8dd9)
