### ISSUE TITLE
youtube-dl + your favourite video player as YouTube alternative?

### ISSUE THREAD

**Issue by l0b0** [tycrek/degoogle#20]
[`youtube-dl`](https://github.com/ytdl-org/youtube-dl/) works with lots of sites, is constantly being updated when the sites change, and avoid the whole issue of browser based tracking by simply downloading the video page and then the video file itself.

**Comment by allevaton** [comment]
VLC can also play YouTube videos via Media > Open Network Stream. I use it quite often.

https://www.vlchelp.com/play-youtube-videos-vlc-media-player/

**Comment by tycrek** [comment]
I'd be willing to add this if you could provide a way of finding a video to watch without using the YouTube interface. They could still track your searches, even if you don't use the site to watch the video

**Comment by l0b0** [comment]
@tycrek @allevaton's suggestion is completely different to mine, and should IMO be a separate issue. `youtube-dl` allows you to use *any* video player instead of the YouTube interface, and they can't track anything when you play the video locally.

**Comment by arp242** [comment]
mpv can also play YouTube directly FYI: `mpv 'https://www.youtube.com/watch?v=cj02_UeUnGQ'`

**Comment by tycrek** [comment]
VLC, youtube-dl, and mpv are all great, *but* that still doesn't answer my question from January 8th on how exactly one would *search* for a video privately before having the opportunity to download or view it using those tools.
