### ISSUE TITLE
Some additions to News, Blogger/Sites, Hangouts, Keep, Maps and new Categories: Backup&Sync to Google Account, Find my Device

### ISSUE THREAD

**Issue by peterge1998** [tycrek/degoogle#21]
- News
  - Setup your own RSS Feed with Open Source tools like TTRSS, FreshRSS, Miniflux
- Blogger/Sites 
  - [Ghost](https://ghost.org/) Open Source, Selfhosted Blog Platform/CMS
- Hangouts
  - [Conversations](https://conversations.im/) (Android | ca. 2$ on Google Play | free on F-Droid) (Cant look up the exact price in USD now) Jabber/XMPP Client, decentral, end to end encrypted and quite similiar to the Matrix protocol
- Keep
  - Nextcloud Notes ( [Google Play](https://play.google.com/store/apps/details?id=it.niedermann.owncloud.notes&hl=en_US) | [F-Droid](https://f-droid.org/en/packages/it.niedermann.owncloud.notes/))to write and sync Notes to an existing Nextcloud Instance
- Backup and Sync to Google Account (Contacts, Calendar, Wifi Password, Settings, Applications, etc.)
  - [DAVx5](https://www.davx5.com/) Sync Android Contacts and Calendars to an existing Nextcloud Instance
  - [Titanium Backup](https://www.titaniumtrack.com/titanium-backup.html) Backup applications including data and more things like settings, wifi passwords, etc.
- Find my Device
  - Find my Phone ([F-Droid](https://f-droid.org/en/packages/se.erikofsweden.findmyphone/)) Respondes with the current GPS Postition to incoming SMS
  - Finder ([F-Droid](https://f-droid.org/en/packages/ru.seva.finder/)) Remote mobile phone searching via SMS-requests. 
  - PhoneTrack ([F-Droid](https://f-droid.org/en/packages/net.eneiluj.nextcloud.phonetrack/)) Logs positions to Nextcloud PhoneTrack app or any custom server 
- Maps
  - MAPS.ME ([Google Play](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro&hl=de) | [F-Droid](https://f-droid.org/en/packages/com.github.axet.maps/)) Maps Application wich is based on OpenStreetMaps with offline track recording. F-Droid Version is Open Source and has no tracker/ads.

**Comment by dimqua** [comment]
Maps.me is already included.

**Comment by tycrek** [comment]
Ghost looks great, I'm considering testing it out for myself. Thanks for the recommendations.

**Comment by licaon-kter** [comment]
Conversations (and forks like Quicksy, Pix-Art Messenger, Snikket and Conv6ations) are on F-Droid and have Audio/Video calls, encryption, are decentralized, etc. so why aren't they on the list?
