### ISSUE TITLE
[NEW] New alternative

### ISSUE THREAD

**Issue by matteocontrini** [tycrek/degoogle#215]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [x] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: Qboxmail
  - **Alternative URL**: https://www.qboxmail.com/
  - **5/9/14 eyes**: yes
  - **Description**: Paid email provider, located in Italy.
- **FLOSS**
  - Repository: /
  - Active: /
  - Download: /
  - Price: paid
  - Self-host: no
- **Encryption**
  - HTTPS: yes
  - E2EE: no
  - Modern Encryption: ?
- **Transparency**
  - Public ownership: yes, Welcome Italia Group
  - 3rd-party audits: no?
- **Privacy**
  - Anonymous payments: no
  - Analytics: unknown
  - Captcha: Google reCAPTCHA
- **Extras**
  - .onion address: no
  - Warrant canary: no

**Comment by tycrek** [comment]
14 eyes (Italy), not open source, Google Captcha.

From their [privacy policy](https://www.qboxmail.com/privacy/):

> We don’t share any personally identifying information publicly or with third-parties, **except when required to by law**.

This is a big issue considering it is 14-eyes.

**Comment by matteocontrini** [comment]
> This is a big issue considering it is 14-eyes.

That also applies to Fastmail, which is in the list. (And I would definitely want it to be/stay in the list...)

**Comment by tycrek** [comment]
> That also applies to Fastmail

That's a good point and must have been missed or not considered when it was added. I'd suggest [opening a new Issue](https://github.com/tycrek/degoogle/issues/new/choose) proposing to remove Fastmail. I feel the only cases in which an eyes service should be considered is when E2EE is used. Fastmail is also not open source which is worth noting in the new issue.

I'm sure there are many others that fall under these terms and should be removed. This guide has changed over time and some services were added at a time when we didn't consider the same things we do now. https://github.com/tycrek/degoogle/issues/131 discusses criteria that did not exist at the time Fastmail was added.
