### ISSUE TITLE
[NEW] New alternative for blogging - Simpleblog

### ISSUE THREAD

**Issue by mawise** [tycrek/degoogle#218]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [x] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: { Simpleblog }
  - **Alternative URL**: { https://simpleblogs.org/}
  - **5/9/14 eyes**: { No--might depend on self-hosted vs paid/AWS hosting? Is AWS 5/9/14 eyes?}
  - **Description**: { FLOSS blogging platform with a focus on privacy.  Easy to self-host (standard rails app, ships with AWS deployment scripts).  Access restricted to accounts which you create and hand out.  Good for private blogs but not for commercial/public blogging. }
- **FLOSS**
  - Repository: { https://github.com/mawise/simpleblog }
  - Active: { yes } (any branch in source repo active within past four months, excluding translations)
  - Download: { Source on Github } (Direct is direct downloads, such as GitHub releases)
  - Price: { freemium - paid option for hosting, free to self-host } (free: no payments at all; paid: no free tier excluding trials; freemium: any mix of free tier and paid plans)
  - Self-host: { yes } (use "only" if the only option is self hosting; for example, LibreOffice Online)
- **Encryption**
  - HTTPS: { yes }
  - E2EE: { yes }
  - Modern Encryption: { yes }
- **Transparency**
  - Public ownership: { no } [Parent company name](https://parent.company.url)
  - 3rd-party audits: { no } [Link to audit history](https://audit.history.url)
- **Privacy**
  - Anonymous payments: { no } (these types of payments can include cash, cryptocurrency, gift cards)
  - Analytics: { no } { type of analytics }
  - Captcha: { none }
- **Extras**
  - .onion address: { .onion address }
  - Warrant canary: { no }

**Comment by tycrek** [comment]
AWS is in 5/9/14 eyes jurisdiction, and AWS itself is not privacy friendly. Does the project require an AWS server to operate or does self-host work on any Linux server?

**Comment by mawise** [comment]
Self host can be on any Linux server
