### ISSUE TITLE
[NEW] New alternative - analytics - Piwik PRO

### ISSUE THREAD

**Issue by Marcin-PiwkPRO** [tycrek/degoogle#226]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [X ] **I am affiliated with this alternative**
- [ X] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: { Piwik PRO }
  - **Alternative URL**: { https://piwik.pro/ }
  - **5/9/14 eyes**: { no }
  - **Description**: { Piwik PRO is the privacy oriented alternative to Google Analytics. Created in 2013, Piwik PRO Analytics Suite allows for tracking web, app, product and intranet behavior of users. The platform ensures compliance with strict EU, US, Chinese and Russian data protection laws, including the General Data Protection Regulation (GDPR) and the Health Insurance Portability and Accountability Act (HIPAA). 

Piwik PRO serves over 200 customers from around the world including governments, public institutions, private companies and enterprises. Piwik PRO has been chosen by such organizations as the Government of the Netherlands, the Government of Finland, the European Commission, Credit Agricole, HP, and Accenture.
 }
- **FLOSS**
  - Repository: {N/A }
  - Active: { N/A } 
  - Download: { N/A } 
  - Price: { paid} (
  - Self-host: { yes } 
- **Encryption**
  - HTTPS: { yes }
  - E2EE: { no}
  - Modern Encryption: { yes }
- **Transparency**
  - Public ownership: { no } 
  - 3rd-party audits: { yes } [3rd party, yearly security audit & [ISO 27001-certified](https://uploads.piwik.pro/piwik.pro/2018/08/Piwik-PRO-Certificate_EN-1.png)]
- **Privacy**
  - Anonymous payments: { no } 
  - Analytics: { yes }
  - Captcha: { NO }
- **Extras**
  - .onion address: { N/A }
  - Warrant canary: {no }

**Comment by Marcin-PiwkPRO** [comment]
@tycrek thanks for adding us to the list. Our name is Piwik PRO, could you please change the "Pro" into "PRO"? :)

**Comment by tycrek** [comment]
> 
> 
> @tycrek thanks for adding us to the list. Our name is Piwik PRO, could you please change the "Pro" into "PRO"? :)

Fixed in https://github.com/tycrek/degoogle/commit/cbf61533d0933e4ecc39dad943781e771a7b3f5e 👍
