### ISSUE TITLE
Public transport app

### ISSUE THREAD

**Issue by lgiard** [tycrek/degoogle#24]
There are at least 2 popular public transport app on fdroid : 
- Transportr (with a small 'r' after the 't') which is opensource and allow to calculate route on public transport in various countries. It is simple visually and in usage.
- Offi : Another open source app with 3 parts - one for directions (routing), one for informations about the stations (what is the next bus/train/... at the nearby stations) and one for plans (some cities have their public transport plans in the apps). It feel more complex and complete.

Both are complementary and offer services in places where the public transport companies offer open feed to get the schedule and information live. They are multi-modal so it helps when having to take multiple transport too. It works generally well in western Europe as far as i know, but i never tested in other place.

**Comment by tycrek** [comment]
Thank you, I'll add them in the next update.
