### ISSUE TITLE
Multiple suggestions (Photos, Drive, Search, Map, Fonts)

### ISSUE THREAD

**Issue by mynamesleon** [tycrek/degoogle#25]
First, another good source site to use for alternatives is [switching.software](https://switching.software/) - might be worth adding to the intro as well.

As for some suggestions:

1. **Photos**: [JottaCloud](https://jottacloud.com) (not E2EE, but based in Norway, on green energy, and with a [privacy guarantee](https://jottacloud.com/en/guarantee.html) - 5gb free tier), and [Crypt.ee](https://crypt.ee) (relatively young, so no native apps yet, but is E2EE - tiny free tier though).
2. **Drive**: [JottaCloud](https://jottacloud.com) (again), and [Sync.com](https://sync.com) (E2EE, with 5gb free tier). Also re NextCloud - might want to point out that there are lots of [hosted NextCloud solutions](https://nextcloud.com/providers/) available too, for those unable to self-host)
3. **Search**: [Ekoru](https://ekoru.org/) (much like Ecosia, but for ocean cleanup, and with a better privacy policy)
4. **Map**: [Qwant Maps](https://www.qwant.com/maps/) (uses OpenStreetMap data, but their geocoding seems to be slightly better subjectively - dependent on WebGL being enabled in your browser)
5. **Fonts**: [Font Squirrel](https://www.fontsquirrel.com/) (includes some free fonts, but you can also upload fonts to generate webfonts for self-hosting)

**Comment by dimqua** [comment]
Also https://benmaps.fr/

**Comment by tycrek** [comment]
Switching.software looks awesome, thanks. Same with Ekoru, JottaCloud, and Qwant Maps.

Crypt.ee is already listed and the description mentions photos. Sync.com was also recently added in a PR. [Font Squirrel's privacy policy](https://www.fontsquirrel.com/privacy) is too restrictive for privacy.
