### ISSUE TITLE
[NEW] New alternative to Analytics: Umami

### ISSUE THREAD

**Issue by codingepaduli** [tycrek/degoogle#250]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **General**
  - **Alternative name**: Umami
  - **Alternative URL**: https://umami.is/
  - **5/9/14 eyes**: unknown
  - **Description**: Umami is a simple, easy to use, self-hosted web analytics solution.
- **FLOSS**
  - Repository: https://github.com/mikecao/umami
  - Active: yes
  - Download: Direct
  - Price: free
  - Self-host: only
- **Encryption**
  - HTTPS: yes
  - E2EE: yes/no/optional ??
  - Modern Encryption: yes/no ??
- **Transparency**
  - Public ownership: yes/no 
  - 3rd-party audits: no 
- **Privacy**
  - Anonymous payments: yes/no ??
  - Analytics: yes/no ??
  - Captcha: recaptcha/hcaptcha/other ??

**Comment by tycrek** [comment]
This looks really nice, thanks for sharing. I'll add it in the next update
