### ISSUE TITLE
[REMOVE] Delist all Zoho products

### ISSUE THREAD

**Issue by hagardeviking** [tycrek/degoogle#256]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [ ] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **Alternative name**: zoho.com
- **Reason**: Does not satisfy security criteria

Hey, although I think Zoho services are great and a pretty good alternative to GSuite, unfortunately  I do not think they meet the latest security requirements as indicated in #215 

1. Zoho currently host your data in either the US (5👀), EU (5/9/14👀), or AU (5👀) depending on your own location. 
https://www.zoho.com/know-your-datacenter.html
2. Other hosting jurisdictions such as China or India itself are just as bad. For example, India's data protection laws are very new (2019) and at present illegally gained information has been used as evidence in court to achieve conviction. Furthermore at least 16 intelligence agencies are currently active without any clear oversight. And regardless surveillance with gag orders can be legitimised
https://www.buzzfeednews.com/article/pranavdixit/india-home-ministry-surveillance-computers-ten-agencies
https://privacyinternational.org/state-privacy/1002/state-privacy-india
3. Zoho accept they must comply with data requests and gag orders
Last item in their Security FAQ https://www.zoho.com/security-faq.html
4. As for encryption: any mail service that supports IMAP or POP cannot, by definition, provide total E2EE although ProtonMail and others come pretty close. But Zoho does not attempt to do anything like this
5. Further, the keys for any encryption they do use are managed solely by themselves
https://www.zoho.com/encryption.html
6. I do not believe any of their software components are Open Source; only their CRM has been identified as explicitly NOT OSS
https://help.zoho.com/portal/en/community/topic/is-zoho-crm-still-open-source

**Comment by tycrek** [comment]
Those are all very good points, thanks for taking the time to compile that list!

**Comment by tycrek** [comment]
Going to take this opportunity to say this: **Zoho will not be readded**
