### ISSUE TITLE
[FIX] Fix/update alternative Sync to 5-eyes

### ISSUE THREAD

**Issue by adam-sroka** [tycrek/degoogle#263]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [x] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

- **Alternative name**: Sync
- **Error**: It is currently missing that Sync is a part of 5-eyes
- **Proposed changes**: "Eyes" should be set to "5" for Sync
- **Additional details**: See the address in the [About us](https://www.sync.com/about/) section of Sync website or the Sync [Company Overview](https://www.sync.com/download/sync_fact_sheet.pdf) to see that Sync is based in Canada, which is a part of [Five Eyes](https://www.privacytools.io/providers/#ukusa).

**Comment by m0yP** [comment]
Perhaps it ain't listed as such because it's a zero-knowledge service?

**Comment by adam-sroka** [comment]
@m0yP, well, in that case, it would be inconsistent, as other "zero-knowledge" alternatives are labelled with their respective "eyes", for example:
<img width="839" alt="crypt_pad" src="https://user-images.githubusercontent.com/45038919/92511315-a7f31600-f1fc-11ea-8804-4b8df4fa5c3b.png">

I thought any service with its company based in 5, 9 or 14-eyes should be labelled appropriately, as stated in the [Disclaimer](https://github.com/tycrek/degoogle#disclaimer):

> 5-eyes, 9-eyes, and 14-eyes services will be listed, and marked as such. This means the company, not the server IP.

**Comment by m0yP** [comment]
> @m0yP, well, in that case, it would be inconsistent, as other "zero-knowledge" alternatives are labelled with their respective "eyes", for example:
> <img alt="crypt_pad" width="839" src="https://user-images.githubusercontent.com/45038919/92511315-a7f31600-f1fc-11ea-8804-4b8df4fa5c3b.png">
> 
> I thought any service with its company based in 5, 9 or 14-eyes should be labelled appropriately, as stated in the [Disclaimer](https://github.com/tycrek/degoogle#disclaimer):
> 
> > 5-eyes, 9-eyes, and 14-eyes services will be listed, and marked as such. This means the company, not the server IP.

You got me there.
