### ISSUE TITLE
[NEW] Movie suggestion

### ISSUE THREAD

**Issue by nam108** [tycrek/degoogle#268]
Maybe it would be beneficial to add this 50 min document featuring Soshana Zuboff? - Shoshana Zuboff on surveillance capitalism | VPRO Documentary - https://www.youtube.com/watch?v=hIXhnWUmMvw

**Comment by tycrek** [comment]
Ironically, Zuboff's book is already in the guide. Thanks for sharing, I'll add it in the next update.

**Comment by tycrek** [comment]
Forgot to add: I'll add alternate links for Invidious and Hooktube instead of YouTube 😉
