### ISSUE TITLE
Link to info about /e/ contains trashtalk

### ISSUE THREAD

**Issue by kyljys** [tycrek/degoogle#27]
There is a /e/ OS based on LineageOs 16 (pie). It is clearly stated on their website that E-OS is based on Lineage OS. It has a large userbase who really do bring forth issues which are attented to. Everyone can check this personally from their issue tracker page. Issues seem to be fixed reasonably fast given smaller group of contributors. All the issues in the trashtalk link are either solved or on the table.
Eos differs from lineage os and microg for lineageos in that eos tries to remove google from AOSP-code itself, which is mandatory if one really wants to de-google a phone. That alone would make E OS more secure than any of the AOSP or OEM based custom roms.
The text in the afore mentioned link is ill-adviced, biased rant without a reasonable fact checking.

**Comment by ithink314** [comment]
I wouldn't go near eelo with a ten foot pole.

https://github.com/privacytoolsIO/privacytools.io/issues/864#issuecomment-527438454

**Comment by tycrek** [comment]
Because of the amount of controversy surrounding /e/ or Eelo or whatever it's called I've opted to remove it entirely.
