### ISSUE TITLE
[FIX] Analytics

### ISSUE THREAD

**Issue by evanspy1** [tycrek/degoogle#271]
[x]: # ( Fill out to the best of your ability.  )
[x]: # ( If an item is not applicable, feel free to leave it blank. )
[x]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [x] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)** (#270)

### Details

- **Alternative name**: Google Analytics, Ackee
- **Error**: N/A
- **Proposed changes**: Add Ackee Analytics as an alternative to Google Analytics
- **Additional details**: https://ackee.electerious.com/ - I am not the developer or a contributor, but I do use it and it works well.

**Comment by tycrek** [comment]
@evanspy1 would you mind making a new issue with the [proper template](https://github.com/tycrek/degoogle/issues/new?assignees=&labels=&template=new-alternative.md&title=%5BNEW%5D+New+alternative) considering this is a *new* service and not a fix?

**Comment by tycrek** [comment]
Closing to reduce clutter but feel free to open a new Issue with the proper template
