### ISSUE TITLE
[OTHER] Any Pull Requests MUST have an Issue for discussion

### ISSUE THREAD

**Issue by tycrek** [tycrek/degoogle#277]
[//]: # ( Fill out to the best of your ability.  )
[//]: # ( If an item is not applicable, feel free to leave it blank. )
[//]: # ( Mark off checkbox items by putting an x in between the [ ] without spaces, i.e. `[x]` )

### Checklist

- [ ] **I am affiliated with this alternative**
- [x] **I have read the rules outlined in [CONTRIBUTING.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md)**
- [x] **Include my name in [CONTRIBUTORS.md](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTORS.md)**

### Details

Pull Requests are not a great place to discuss alternatives due to how quickly they can get cluttered. Any new PR should already have an issue created.

**Comment by SuperSandro2000** [comment]
Why should I create an issue for a PR like https://github.com/tycrek/degoogle/pull/157 ? This is just noise and clutter.

**Comment by tycrek** [comment]
As mentioned in my post, Issues are used for discussion. They also provide historical reference for why something was changed. This has come up before where we're able to reference old Issues to resolve new ones.

On top of that, the requirement for using both Issues and PR's (brought up in #108) has been in place [since May 15th](https://github.com/tycrek/degoogle/commit/a27cf03b0b2260f70812074dded7087327da6113), I just never properly enforced it. It is also mentioned in #138.

> I won't make it a strict requirement for opening a PR, but it will be recommended to open an Issue first.

This will be changing as I've had far too many headaches with people not properly opening PR's or completely skipping reading the CONTRIBUTING.md guidelines.

I know for things like that where the alternative will obviously be added it might be tedious, but it's just something that people will have to live with. Issues on the other hand do *not* need a Pull Request. This will be clarified in CONTRIBUTING.md when I get around to updating it today.

**Comment by SuperSandro2000** [comment]
I personally will ignore the contributing guideline and just open a PR if I have a change that does not require any discussion. Opening blank issues that have no content does not make anything better. Most of the not useful PRs I have seen here, are just editing the README.md directly and not the yaml files which gets not solved by this.

**Comment by tycrek** [comment]
> I personally will ignore the contributing guideline and just open a PR if I have a change that does not require any discussion

Updated guidelines in the referenced commit. Anything regarding an alternative requires an issue, period. You don't need to fill out every field as that's unrealistic and has never been required. The templates currently state `[//]: # ( If an item is not applicable, such as HTTPS for an App, feel free to leave it blank. )` but it's probably a good idea to have it indicate you can remove any non-applicable lines rather than leave them blank. The current templates are really badly formatted and I'm working on making them better.

> Opening blank issues that have no content does not make anything better

That's why I have the templates. Blank issues are also not permitted (added this rule earlier in CONTRIBUTING.md).

> Most of the not useful PRs I have seen here, are just editing the README.md directly and not the yaml files which gets not solved by this

If they edit the README, they clearly did not read the contributing guidelines. Previously I would make a request to edit the PR, but from this point I will start closing them with a link to that rule. The reason I am making these guidelines is because I'm tired of handholding people who can't take 2 minutes to read one file.

> Also many issues are just Add X which people could directly add instead of delivering all the required information in an issue directly

As I have said many times before, this is for *discussion*. If all the required info is in the PR, then it takes 10 seconds to fill out an issue template. If the PR is done well and the alternative can be added, then I merge it and the issue is closed.

At most, all that's really required is name, URL, and description. Everything else is very helpful on my part as I don't have to research it all and it increases the chances of the issue being closed faster. Another reason why I prefer issues is because many GitHub users don't actually know how to properly do Pull Requests. I give them the opportunity to use an issue and I will add the alternative myself. That's also why I request as much info as possible.

I don't want to seem like an asshole and I do appreciate your input. Every few weeks/months this repo or the GH Pages is posted to Reddit or Hacker News and I get a massive influx of new contributions. The last one had so many I got overwhelmed and ignored most of them for 2 months. I didn't like doing that but having properly formatted contributions makes it literally one click for me to merge, or 2 minutes to read someones issue template and add something.
