### ISSUE TITLE
[NEW] New alternative to google ad

### ISSUE THREAD

**Issue by z3r0n3t** [tycrek/degoogle#281]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes|
| Include my name in [CONTRIBUTORS.md]                | yes|
| I am affiliated with this alternative               | yes|

### Details

- **General**
  - **Alternative name**: Carbon ads 
  - **Alternative URL**: https://www.carbonads.net/
  - **5/9/14 eyes**: unknown
  - **Description**: its a very clean ad service targeting the tech industry and respects privacy 
                                 its goal is to help Tech industry with ads targeting developers
- **FLOSS**
  - Repository:NO 
  - Active: yes/no (any branch in source repo active within past four months, excluding translations)
  - Download: F-Droid/Direct/Play Store (Direct is direct downloads, such as GitHub releases)
  - Price: free/paid/freemium (free: no payments at all; paid: no free tier excluding trials; freemium: any mix of free tier and paid plans)
  - Self-host: yes/no/only (use "only" if the only option is self hosting; for example, LibreOffice Online)
- **Encryption**
  - HTTPS: yes
  - E2EE: unknown 
  - Modern Encryption: yes
- **Transparency**
  - Public ownership: no
  - 3rd-party audits: not applicable 
- **Privacy**
  - Anonymous payments: no
  - Analytics: yes type: unknown 
  - Captcha: unknown 
- **Extras**
  - .onion address: .onion address
  - Warrant canary: no [Link to canary](https://warrant.canary.url)

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by z3r0n3t** [comment]
"If this is for Hacktoberfest 2020, be sure to add the Hacktoberfest label to the PR"
thank you i forgot to do that

**Comment by SuperSandro2000** [comment]
@z3r0n3t You no longer need to do that.

**Comment by z3r0n3t** [comment]
@SuperSandro2000 okay thank you

**Comment by tycrek** [comment]
Not sure why you closed the PR so I'll have to close this too
