### ISSUE TITLE
[REMOVE] Remove Neat URL

### ISSUE THREAD

**Issue by freddy-m** [tycrek/degoogle#289]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **Alternative name**: ClearURLS (it's already listed)
- **Reason**: Neat URL does nothing that ClearURLS can't AFAIK, and having more than one add-on that does the same thing is bad for fingerprinting.

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by freddy-m** [comment]
In general, I feel as though the add-ons section needs a re-do. I know there was on main contributor who created it, and, while it contains good resources, it may lead users to install all of these add-ons which would be terrible for fingerprinting.

**Comment by tycrek** [comment]
Just to confirm: out of the two, which would you suggest stays?

**Comment by freddy-m** [comment]
Keep ClearURLS.
