### ISSUE TITLE
[NEW] New alternative - text/video messaging - GNU Jami

### ISSUE THREAD

**Issue by codedust** [tycrek/degoogle#290]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: GNU Jami
  - **Alternative URL**: https://jami.net/
  - **5/9/14 eyes**: unknown
  - **Description**: Jami is a decentralized video conferencing software similar to Tox. It uses P2P communication and does not rely on centralized servers.
- **FLOSS**
  - Repository: https://git.jami.net/savoirfairelinux
  - Active: yes
  - Download: F-Droid, Play Store, Direct (for desktops), Apple AppStore
  - Price: free
  - Self-host: depends on you definition (one can run servers but one does not need to - same as for Tox)
- **Encryption**
  - HTTPS: does not apply
  - E2EE: yes
  - Modern Encryption: yes/no - what does this mean?
- **Transparency**
  - Public ownership: yes/no [Parent company name](https://parent.company.url)
  - 3rd-party audits: yes/no [Link to audit history](https://audit.history.url)
- **Privacy**
  - Anonymous payments: no / n/A
  - Analytics: no
  - Captcha: no
- **Extras**
  - .onion address: .onion address
  - Warrant canary: yes/no [Link to canary](https://warrant.canary.url)

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Was added in https://github.com/tycrek/degoogle/commit/3552ba7004175e9372e0e2064897ff793b09a503
