### ISSUE TITLE
[NEW] New alternative - Öffi

### ISSUE THREAD

**Issue by codedust** [tycrek/degoogle#292]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: Öffi
  - **Alternative URL**: https://oeffi.schildbach.de/
  - **5/9/14 eyes**: yes/no/unknown - build in Germany, unsure about hosting
  - **Description**: Öffi is a public transport Android app (also shows delays and replacement bus service for more and more transport authorities in Europe and beyond) - similar to Transportr
- **FLOSS**
  - Repository: https://gitlab.com/oeffi/oeffi
  - Active: yes
  - Download: F-Droid, Direct, Play Store
  - Price: free
  - Self-host: no (would probably be possible in theory but not promoted/supported)
- **Encryption**
  - HTTPS: yes
  - E2EE: no
  - Modern Encryption: yes/no
- **Transparency**
  - Public ownership: yes/no [Parent company name](https://parent.company.url)
  - 3rd-party audits: yes/no [Link to audit history](https://audit.history.url)
- **Privacy**
  - Anonymous payments: no / n/A
  - Analytics: no
  - Captcha: no
- **Extras**
  - .onion address: .onion address
  - Warrant canary: yes/no [Link to canary](https://warrant.canary.url)

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by codedust** [comment]
I just noticed that Öffi is already included in the `Mobile apps > Maps/Waze` section but is missing in the `Web-based products > Transit` section.

**Comment by tycrek** [comment]
> 
> 
> I just noticed that Öffi is already included in the `Mobile apps > Maps/Waze` section but is missing in the `Web-based products > Transit` section.

It isn't in web-based since it's a mobile app. Although I will update the existing description to the one you provided as it is much better.

**Comment by codedust** [comment]
Thank you for maintaining this great list!
