### ISSUE TITLE
[REMOVE] Remove Decentraleyes

### ISSUE THREAD

**Issue by freddy-m** [tycrek/degoogle#293]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **Alternative name**: `privacy.firstparty.isolate` in`about:config`
- **Reason**: it [doesn't actually work](https://github.com/arkenfox/user.js/issues/948) as the resources are [horribly out of date](https://git.synz.io/Synzvato/decentraleyes/-/tree/master/resources). [Thorin-Oakenpants](https://github.com/arkenfox) does [describe](https://github.com/privacytools/privacytools.io/issues/1430#issuecomment-704335991) why FPI is really the only way to achieve these addons set out to do.

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Not too sure what FPI is exactly. Could you open a new issue describing it?
