### ISSUE TITLE
[REMOVE] Remove ToS;DR

### ISSUE THREAD

**Issue by freddy-m** [tycrek/degoogle#294]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes|
| Include my name in [CONTRIBUTORS.md]                | yes|
| I am affiliated with this alternative               | no |

### Details

- **Alternative name**: [PrivacySpy](https://privacyspy.org/)
- **Reason**: ToS;DR is dead and PrivacySpy is actively maintained and generally sleeker.

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Mind making a [new Issue](https://github.com/tycrek/degoogle/issues/new/choose) for PrivacySpy?
