### ISSUE TITLE
[NEW] New alternative to hangouts(video/meeting)

### ISSUE THREAD

**Issue by Hardik0307** [tycrek/degoogle#295]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: Jami
  - **Alternative URL**: https://jami.net/
  - **5/9/14 eyes**: unknown
  - **Description**: It's FOSS, distributed, and secure video/audio conferencing application.
- **FLOSS**
  - Repository:https://git.jami.net/savoirfairelinux/ring-project/wikis/home
  - Active: yes
  - Download: https://jami.net/download/
  - Price: free
  - Self-host: yes/no/only (use "only" if the only option is self hosting; for example, LibreOffice Online)
- **Encryption**
  - HTTPS: yes
  - E2EE: yes
  - Modern Encryption: yes/no
- **Transparency**
  - Public ownership: yes
  - 3rd-party audits: no 
- **Privacy**
  - Anonymous payments: no
  - Analytics: unknown
  - Captcha: unknown
- **Extras**
  - .onion address: .onion address
  - Warrant canary: no 

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by Hardik0307** [comment]
Will make PR on it @tycrek.

**Comment by tycrek** [comment]
Added earlier in https://github.com/tycrek/degoogle/commit/3552ba7004175e9372e0e2064897ff793b09a503
