### ISSUE TITLE
[NEW] New alternative

### ISSUE THREAD

**Issue by shivasagarrao** [tycrek/degoogle#307]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: Session
  - **Alternative URL**: https://getsession.org/
  - **5/9/14 eyes**: unknown
  - **Description**: Session is open source. It is an end-to-end encrypted messenger that removes sensitive metadata collection. No phone number required to create an account. 
- **FLOSS**
  - Repository: https://github.com/loki-project/session-android
  - Active: yes
  - Download: Direct/Play Store
  - Price: free
  
[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Thank you for the great suggestions in #306 and #307!

**Comment by asmaier** [comment]
Session admits in it's FAQ, that they are based in Australia, a 5 eyes country. 

https://getsession.org/faq#australia-anti-encryption

Maybe the table should be updated.
