### ISSUE TITLE
Adding iOS Alternatives?

### ISSUE THREAD

**Issue by bobmatyas** [tycrek/degoogle#310]
### Details

I really like this project and would be interested in adding the alternatives for iOS. What is the best way to go through and add some? I'd love to update this list, I just want to be sure to do it in a way that makes sense.

**Comment by tycrek** [comment]
It would probably be best to go through the [Mobile Apps](https://github.com/tycrek/degoogle#mobile-apps) section and see what you can find for each one, both on the App Store and through GitHub via sideloading.

As for Issues.... I do prefer one Issue per alternative; if it's not too much hassle I'd appreciate that. What you could do with the Issues is fill out just **General** in the [New alternative template](https://github.com/tycrek/degoogle/issues/new?assignees=&labels=new&template=new-alternative.md&title=%5BNEW%5D+New+alternative), then connect all of them with another Issue (no template needed) and link back to here as well.

**Comment by bobmatyas** [comment]
Great, I'll go through and add some soon. Thanks!
