### ISSUE TITLE
[OTHER] Table formatting

### ISSUE THREAD

**Issue by nglaeser** [tycrek/degoogle#315]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Details
Small thing: the table (eyes/countries) in list item 5 of the Disclaimers in the website version is not formatted properly. Screenshot (https://degoogle.jmoore.dev/ accessed on Firefox 83.0):
<img width="540" alt="Screenshot" src="https://user-images.githubusercontent.com/17152809/102427362-2cfd8080-3fdf-11eb-8391-bcccd80ceb2e.png">

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
fixed:

![image](https://user-images.githubusercontent.com/29926144/110511782-d37a8e80-80c1-11eb-9079-aa87eb30df83.png)

not the prettiest but it works.
