### ISSUE TITLE
[NEW] New launcher

### ISSUE THREAD

**Issue by J053Fabi0** [tycrek/degoogle#318]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | [yes](https://github.com/tycrek/degoogle/pull/319) |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: Last Launcher
  - **Alternative URL**: https://f-droid.org/packages/io.github.subhamtyagi.lastlauncher/
  - **5/9/14 eyes**: unknown
  - **Description**: It is a really good launcher.
- **FLOSS**
  - Repository: https://github.com/SubhamTyagi/Last-Launcher
  - Active: yes
  - Download: [F-Droid](https://f-droid.org/packages/io.github.subhamtyagi.lastlauncher/)
  - Price: free

- **Transparency**
  - Public ownership: I don't know
  - 3rd-party audits: no
- **Privacy**
  - Analytics: no

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Note from the F-Droid page:
> Note: This app is unmaintained, its app repository is archived by the dev
