### ISSUE TITLE
Classroom Alternative: Edmodo

### ISSUE THREAD

**Issue by MrPeker** [tycrek/degoogle#32]
Edmodo is an educational technology company offering a communication, collaboration, and coaching platform to K-12 schools and teachers. 

https://new.edmodo.com/

**Comment by jankapunkt** [comment]
Also there are self hosted alternatives:

* MOODLE - https://moodle.org/
* ILIAS - https://www.ilias.de/en/

**Comment by tycrek** [comment]
Thanks @jankapunkt , I'll add those in.

@MrPeker , can you find info on whether Edmodo is privacy focused or open source?
