### ISSUE TITLE
[NEW] G-Suite alternative - Sandstorm

### ISSUE THREAD

**Issue by Michael-S** [tycrek/degoogle#321]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no | 
(I have one or two pull requests accepted to their docs, nothing more)

### Details

- **General**
  - **Alternative name**: Sandstorm
  - **Alternative URL**: sandstorm.io
  - **5/9/14 eyes**: yes, 5 eyes
  - **Description**: Sandstorm is an open source web hosting platform for a wide set of web applications, including Etherpad (collaborative text editing), Radicale (calendar), Lychee (image hosting), Wekan (Kanban)
- **FLOSS**
  - Repository: https://github.com/sandstorm-io/sandstorm
  - Active: yes
  - Download: direct
  - Price: free
  - Self-host: only
- **Encryption**
  - HTTPS: yes
  - E2EE: yes, though I do not believe stored data is encrypted on-disk
  - Modern Encryption: yes
- **Transparency**
  - Public ownership: contributors, no company
  - 3rd-party audits: no
- **Privacy**
  - Anonymous payments: no payments
  - Analytics: no
  - Captcha: no
- **Extras**
  - .onion address: no
  - Warrant canary: no

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by virtadpt** [comment]
+1.  I've been running the Sandstorm instance at $dayjob for about three years now, and everybody loves it.

(Sample size: 75 daily users)
