### ISSUE TITLE
[FIX] Fix/update Nextcloud as mail provider

### ISSUE THREAD

**Issue by much-doge** [tycrek/degoogle#324]
Nextcloud is not a mail server, no apps(plugin) in the Nextcloud provided such function either. What it's capable of is as a mail client. There are it's own mail client and rainloop for nextcloud. Not a mail server. The alternative can be, to change the description: 

~Now also provides an email service (self-hosted).~ Thanks @je-vv
Nextcloud only provides webmail interface that can be used to access email from various provider. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

**Comment by tycrek** [comment]
PR merged, closing
