### ISSUE TITLE
[NEW] For Youtube 

### ISSUE THREAD

**Issue by SerjSX** [tycrek/degoogle#329]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no, i have no connection with the developer.|

### Details

- **General**
  - **Alternative name**: NewPipe. 
 Required
  - **Alternative URL**: https://newpipe.net/ 
  Required
  - **5/9/14 eyes**: unknown
  - **Description**: This Youtube alternative is safe, doesn't have any trackers and doesn't need you to login either. It just needs your subscription list file from your Google account and you're good to go. This is one of the best alternatives for Youtube for Android devices, open source, free and secure. 
- **FLOSS**
  - Repository: https://github.com/TeamNewPipe/NewPipe 
  - Active: yes (any branch in source repo active within past four months, excluding translations)
  - Download: https://f-droid.org/en/packages/org.schabi.newpipe/
  - Price: free
  - Self-host: i dont know. 
- **Encryption**
  - HTTPS: yes
  - E2EE: i dont know. 
  - Modern Encryption: i dont know. 
- **Transparency**
  - Public ownership: yes [Team NewPipe] [No general link other than their main site which is above] 
  - 3rd-party audits: i dont know. 
- **Privacy**
  - Anonymous payments: no, unless donation. 
  - Analytics: no, i dont know. 
  - Captcha: i dont know, i haven't seen any captcha's. 

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
this has been in the guide since the original 2018 reddit guide
