### ISSUE TITLE
Edit AuroraStore in Playstore Alternatives

### ISSUE THREAD

**Issue by RefexHD** [tycrek/degoogle#33]
It says that it is an for of YalpStore what it was but isn't anymore in their [readme](https://gitlab.com/AuroraOSS/AuroraStore/blob/master/README.md)  it says 

> While Aurora Store was originally based on Sergei Yeriomin's Yalp store, v3.0 is a clean & complete rewrite from scratch that follows Material Design and runs on all devices running Android 5.0+.

**Comment by tycrek** [comment]
Thanks for clarification, I'll update the listing.

**Comment by RefexHD** [comment]
@tycrek could you remove me from the Credits? The reason is because I plan on deleting this Account.
