### ISSUE TITLE
[REMOVE] Remove Porkbun

### ISSUE THREAD

**Issue by freddy-m** [tycrek/degoogle#331]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **Alternative name**: Njalla, which is already listed.
- **Reason**: Most providers provide free WHOIS privacy. Namecheap does, however they are not listed. Thats becuase they also use extensive trackers on their homepage. The same can be said for Porkbun, and, given the alternatives, I think it should be removed.

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
![image](https://user-images.githubusercontent.com/29926144/110515085-3b7ea400-80c5-11eb-9c4b-cac8415be446.png)

YIKES, that's getting removed for sure
