### ISSUE TITLE
[NEW] Gboard Alternative: FlorisBoard

### ISSUE THREAD

**Issue by Glitchy-Tozier** [tycrek/degoogle#334]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: ????????
  - **Alternative URL**:  ????????
  - **5/9/14 eyes**: unknown
  - **Description**: A feature-rich but well-designed keyboard. It requires no permissions and has very active development.
- **FLOSS**
  - Repository: https://github.com/florisboard/florisboard
  - Active: yes
  - Download: F-Droid/Direct/Play Store
  - Price: free
  - Self-host: ?????
- **Transparency**
  - Public ownership: ?????
  - 3rd-party audits: ?????
- **Privacy**
  - Analytics: Requires no permissions, so probably no.

**Comment by Glitchy-Tozier** [comment]
You wrote "tThis"  ;)

**Comment by tycrek** [comment]
done :D
