### ISSUE TITLE
[NEW] Gboard Alternative: 8Vim

### ISSUE THREAD

**Issue by Glitchy-Tozier** [tycrek/degoogle#335]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: ?????????
  - **Alternative URL**: https://www.8vim.com/
  - **5/9/14 eyes**: Open source, owned by an Indian guy. No idea what eyes that gives it.
  - **Description**: A very different approach to what mobile keyboards should look like. Its concept is inspired by the motions performed in handwriting.
- **FLOSS**
  - Repository: https://github.com/flide/8VIM
  - Active: yes
  - Download: F-Droid/Direct/Play Store
  - Price: free/
  - Self-host: ??????????
- **Transparency**
  - Public ownership: ??????????
  - 3rd-party audits: ??????????
- **Privacy**
  - Anonymous payments: ??????????
  - Analytics: I don't think so; it's open source and requires no permissions.
  - Captcha: ??????????

**Comment by Glitchy-Tozier** [comment]
Actually, devellopment for this app was paused or an indefinite amount of time. So you can close this issue if you want.

**Comment by tycrek** [comment]
I like the idea of it, and the latest commits are relatively recent. I'll add it for now.
