### ISSUE TITLE
Nextcloud is very powerfull

### ISSUE THREAD

**Issue by chribre** [tycrek/degoogle#34]
Hi and thank's a lot for the Listing. I think it's important work you're doing here. I'd like to mention that Nextcloud with its intern Appstore and Clients is a quite complex Solution for some of the here mentioned tasks. NC was critical for me to degoogle myself and I think everyone interested in the topic should have a look. Contact/Calender/Task-sync, a newsapp and together with collabora a real good alternative to google docs. There's a lot of community support and it's really easy to start your own instance. 
I'm totally in Love with this project and I think it's the biggest bundle of solutions as alternative to google. 

best regards,
Christian

**Comment by DatAres37** [comment]
It's already mentioned tho.

**Comment by tycrek** [comment]
Thank you for the kind words! It's nice to see that people appreciate this guide.

I already have NC listed for Drive and Mail. I'll add a note for Contacts and Calendar support.

Would you be able to open a new issue with a link for Collabora?
