### ISSUE TITLE
[NEW] LibreTranslate

### ISSUE THREAD

**Issue by infectormp** [tycrek/degoogle#341]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: LibreTranslate
  - **Alternative URL**: https://libretranslate.com/
  - **5/9/14 eyes**: unknown
  - **Description**: Free and Open Source Machine Translation API, entirely self-hosted
- **FLOSS**
  - Repository: https://github.com/uav4geo/LibreTranslate
  - Active: yes 
  - Download: Direct
  - Price: free
  - Self-host: yes
- **Transparency**
  - Public ownership: yes [Argos Open Technologies ](https://www.argosopentech.com/)
  - 3rd-party audits: no

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
this actually looks very cool, thank you
