### ISSUE TITLE
[OTHER] Translating into Turkish Language

### ISSUE THREAD

**Issue by melikechan** [tycrek/degoogle#343]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |

### Details

Hello there, 

I would like to translate this repo in Turkish. In Turkey, a lot of device users use big companies' products. (including Google, of course)
I thought that if someone starts translating into Turkish, more people that use Turkish would help. For me, it would be a pleasure to make this repo more reachable.

Repo link: https://github.com/melikechan/degoogle-turkish (Turkish language branch for latest or master)

Stay safe, hoping you would appreciate it!

**Comment by tycrek** [comment]
thank you!
