### ISSUE TITLE
[OTHER] Mirror?

### ISSUE THREAD

**Issue by retiolus** [tycrek/degoogle#349]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Details

I don't know if this can count as a mirror, but I'm basing myself on this project to improve it according to my vision and to translate it into as many languages as possible (for the moment translated into French. Spanish, Italian and Catalan are currently being translated).

[https://github.com/retiolus/privacysec](https://github.com/retiolus/privacysec)

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
@retiolus Looks interesting, I don't think it fits as an alternative or mirror however I wouldn't be opposed to including it in the [Resources section](https://github.com/tycrek/degoogle#resources). Any suggestion for a description?

**Comment by retiolus** [comment]
Maybe "Another list of free, open source and privacy respecting services and alternatives to privatize services whose aim is to be translated into as many languages as possible"
