### ISSUE TITLE
[REMOVE] Remove alternative

### ISSUE THREAD

**Issue by retiolus** [tycrek/degoogle#350]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Details

- **Alternative name**: DuckDuckGo
- **Reason**: I don't know why should DuckDuckGo remain in this list after reading this: [lemmy.ml/post/31321](https://lemmy.ml/post/31321)

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by danarel** [comment]
While the stuff listed is interesting, the author sadly doesn't link to anything substantial. It doesn't mean they are lying or wrong, but that they are not making a compelling case by linking to Wikipedia, Reddit, and some other dead links.

While some of the DDG partners have violated user privacy, I don't think that automatically disqualifies DDG. 

In the end, I would like to see more credible evidence to back up these claims before joining the choir to remove them from privacy sites.

**Comment by danarel** [comment]
Further research into "dirtfinder" is reason enough to close this request. They have nothing but a history of complaining about any and every service online. They should unplug.

https://lemmy.ml/u/dirtfindr - yikes.

**Comment by retiolus** [comment]
You can try by yourself, make a search with DDG, inspect element, network, highlight some text:
3 requests to improving.duckduckgo.com, in my case uBlock origin blocked this requests.

![image](https://user-images.githubusercontent.com/65604466/111144288-ca386880-857e-11eb-9034-cc7392da3b27.png)
