### ISSUE TITLE
[NEW] Browser: Ghostery

### ISSUE THREAD

**Issue by hf-checking** [tycrek/degoogle#353]
[//]: # Browser: Ghostery

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General** Ghostery Browser
  - **Alternative name**: Ghostery Browser and Ghostery Extension
  - **Alternative URL**: www.ghostery.com
  - **5/9/14 eyes**: unknown
  - **Description**: Nice fast browser with privacy first

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by Glitchy-Tozier** [comment]
Ghostery has a really bad privacy-reputation. No idea whether that browser is developed by the same people behind the adblocker though.

**Comment by hf-checking** [comment]
I've been reading that it's a German company and didn't read about bad reputation. I've noticed that they have something called ghost rank but you have to opt-in for that. So I wonder where you have found that info.

**Comment by Glitchy-Tozier** [comment]
I don't have any big sources, it's just that this seems to be a general cosensus on a reddit-forum (r/privacy). I think it was them (ghostery) exposing tons of user-data some years ago, but i am not 100% sure.

**Comment by tycrek** [comment]
Considering most of their truly helpful privacy features are [paywalled](https://www.ghostery.com/pricing/), I'd opt to not add it at this time. The features in the Free plan can easily be accomplished with other items in the guide.
