### ISSUE TITLE
[NEW] /e/OS (e.foundation) Android alternative

### ISSUE THREAD

**Issue by KevinFanch** [tycrek/degoogle#357]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | yes |

### Details

- **General**
  - **Alternative name**: /e/
  - **Alternative URL**: e.foundation
  - **5/9/14 eyes**: unknown
  - **Description**: It is easy to use for non-technical mobile phone users, improves their privacy.
- **FLOSS**
  - Repository: https://gitlab.e.foundation/
  - Active: yes
  - Download: Direct
  - Price: free or freemium (optional)
  - Self-host: yes or no (optional)
- **Encryption**
  - HTTPS: yes
  - E2EE: yes (being implemented)
  - Modern encryption: 
- **Transparency**
  - Public ownership: yes
  - 3rd-party audits: no
- **Privacy**
  - Anonymous payments: no
  - Analytics: no
  - Captcha: no
- **Extras**
  - Warrant canary: no

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Closing due to #55, please move any further discussion of /e/ to that issue.
