### ISSUE TITLE
[NEW] New alternative to Chrome on Android | Android Browser | Privacy Browser

### ISSUE THREAD

**Issue by samcross021** [tycrek/degoogle#368]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: Privacy Browser
  - **Alternative URL**: https://www.stoutner.com/privacy-browser/
  - **5/9/14 eyes**: Unknown
  - **Description**: Privacy Browser is an open source Android web browser focused on user privacy. It is released under the GPLv3+ license. Privacy sensitive features are disabled by default in Privacy Browser. If one of these technologies is required for a website to function correctly, the user may choose to turn it on for just that visit. Or, they can use domain settings to automatically turn on certain features when entering a specific website and turn them off again when leaving.
- **FLOSS**
  - Repository: The source code is available from gitweb.stoutner.com.
  - Active: Yes
  - Download: The standard version is available on F-Droid, Google Play, the Amazon Appstore, and the Galaxy App Store. The free version has all the features of the standard version with the addition of a banner ad across the bottom of the screen. It is available on Google Play, the Amazon Appstore, and the Galaxy App Store.
  - Price: Freemium
  - Self-host: No
- **Encryption**
  - HTTPS: Yes
  - Modern encryption: Yes
- **Transparency**
  - Public ownership: Yes. 
  - Developer Website: https://www.stoutner.com/privacy-browser/
  - 3rd-party audits: Yes. https://privacytools.io/browsers/#browser
  - https://github.com/privacytools/privacytools.io/issues/1051#issue-472661166
- **Privacy**
  - Analytics: No
 Privacy Browser has two primary goals.

Minimize the data that is sent to the internet.
Minimize the data that is stored on the device.
[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by MTSYuki** [comment]
I have on my phone, and is really great for privacy. One problem though, it needs to keep Android System Webview updated, but the developer mentioned on the website that, on the 3.0 version, will rework the engine and remove the Webview from the app to render websites.

Still, not sure if will be listed right now.

**Comment by samcross021** [comment]
You could keep the warning as "Android WebView Update Needed" for that.

**Comment by MTSYuki** [comment]
> You could keep the warning as "Android WebView Update Needed" for that.

Agree
