### ISSUE TITLE
[OTHER] RethinkDNS + Firewall

### ISSUE THREAD

**Issue by ignoramous** [tycrek/degoogle#372]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | yes |

### Details

RethinkDNS + Firewall is a free, libre, and open source DNS-over-HTTPS client, adblocker, and a firewall for non-rooted Android devices, much in line with [TrackerControl](https://github.com/OxfordHCC/tracker-control-android) (which is already listed).

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
GitHub isn't autoclosing these, great
