### ISSUE TITLE
[FIX] Fix/update CopperheadOS

### ISSUE THREAD

**Issue by thelifeofjay** [tycrek/degoogle#375]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes|
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | yes |

### Details

- **General**
  - **Alternative name**: CopperheadOS
  - **Alternative URL**: https://copperhead.co/android
  - **5/9/14 eyes**: yes
  - **Description**: Secure Android built for encrypted and secure phones by a privacy focused company. 
- **FLOSS**
  - Repository: https://gitlab.com/copperheadsec/os-src
  - Active: yes
  - Download: Direct
  - Price: paid
  - Self-host: yes
- **Encryption**
  - HTTPS: yes
  - Modern encryption: yes
- **Transparency**
  - Public ownership: yes [Copperhead](https://copperhead.co)
- **Privacy**
  - Anonymous payments: yes
  - Analytics: no

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Only just realised this wasn't auto-closed by GitHub, closing now as PR is merged
