### ISSUE TITLE
[REMOVE] ProtonMail

### ISSUE THREAD

**Issue by 89z** [tycrek/degoogle#376]
If you try to create a new account [1], you are presented with these options:

1. CAPTCHA
2. Email
3. SMS
4. Donate

I would argue that 1, 3, 4 are not respecting of privacy. Finally, I tried the email option, but they also block privacy respecting domains such as `mailsac.com`. Because of this, I think ProtonMail should be removed [2], or at least add (another) note about their privacy issues.

1. https://protonmail.com/signup
2. https://github.com/tycrek/degoogle#gmail-mail-service

**Comment by jerryvu26** [comment]
For 2 and 3, they wrote in [this support page](https://protonmail.com/support/knowledge-base/human-verification/), and I quote:
> If you are presented with Email or SMS verification, we only save a cryptographic hash of your email or phone number which is not permanently associated with the account that you create. Because hash functions are one way functions, it is impossible to derive your phone number or email from that hash. However, using the same phone number will result in obtaining the same cryptographic hash, so by comparing hashes, we can detect re-use of phone number or email addresses for human verification.
So yeah, they're safe enough.

I do agree that CAPTCHA and donating are not privacy respecting though, considering the options they have are just credit card or PayPal for donations. And who knows what Google might do to the data they have from reCAPTCHA.

**Comment by jerryvu26** [comment]
For 2 and 3, they wrote in [this support page](https://protonmail.com/support/knowledge-base/human-verification/), and I quote:
> If you are presented with Email or SMS verification, we only save a cryptographic hash of your email or phone number which is not permanently associated with the account that you create. Because hash functions are one way functions, it is impossible to derive your phone number or email from that hash. However, using the same phone number will result in obtaining the same cryptographic hash, so by comparing hashes, we can detect re-use of phone number or email addresses for human verification.

So yeah, they're safe enough.

I do agree that CAPTCHA and donating are not privacy respecting though, considering the options they have are just credit card or PayPal for donations. And who knows what Google might do to the data they have from reCAPTCHA.

**Comment by tycrek** [comment]
Please read the [Contributing guidelines](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md) before opening an Issue or Pull Request.
