### ISSUE TITLE
[REMOVE] Runaroo

### ISSUE THREAD

**Issue by onlyjob** [tycrek/degoogle#381]
Remove disfunctional Runaroo please. It has been discontinued and [attempt to search](https://www.runnaroo.com/search?term=runaroo) brings the following statement:

> I've taken Runnaroo down and not sure if it will be back.
> Thank you to all of those who have used Runnaroo over the last year!
> I'm going to get tacos.
> [Just replied to a HN thread](https://news.ycombinator.com/item?id=26731477)
> -Chris

**Comment by tycrek** [comment]
Please read the [Contributing guidelines](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md) before opening an Issue or Pull Request.

**Comment by onlyjob** [comment]
Wonderful bureaucratic victory over common sense: refuse to remove no longer operational service because a useless template has not been filled.

In other words gift wrap is more important than gift. Disgraceful.
