### ISSUE TITLE
[NEW] search.brave.com

### ISSUE THREAD

**Issue by onlyjob** [tycrek/degoogle#382]
https://search.brave.com/ is a new search engine that might be worth considering for inclusion. Unfortunately is is not an Open Source software but nevertheless an alternative.

**Comment by Shahin-rmz** [comment]
how does it work?

**Comment by onlyjob** [comment]
https://brave.com/search/#search-faq

> Q: What is Brave Search?
> A: Brave Search is the world’s most complete, independent, private search engine. By integrating Brave Search
> beta into its browser, Brave offers the first all-in-one browser / search alternative to the big tech platforms. Brave 
> Search beta is also available in other browsers, at search.brave.com.

**Comment by Shahin-rmz** [comment]
Nice. thanks for sharing though.

**Comment by tycrek** [comment]
Please read the [Contributing guidelines](https://github.com/tycrek/degoogle/blob/master/CONTRIBUTING.md) before opening an Issue or Pull Request.
