### ISSUE TITLE
[NEW] New alternative: Brave Search

### ISSUE THREAD

**Issue by MahbodHastam** [tycrek/degoogle#387]
[//]: # ( Fill out to the best of your ability. )
[//]: # ( If an item is not applicable, feel free to remove the line. )

| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | yes |
| I am affiliated with this alternative               | no |

### Details

- **General**
  - **Alternative name**: Brave Search
  - **Alternative URL**: https://search.brave.com/
  - **Description**: Brave Search doesn’t track you, your searches, or your clicks. *it's on beta stage yet*.

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by onlyjob** [comment]
FYI, this was formerly reported in #382 which was handled in an "interesting" way...
