### ISSUE TITLE
[FIX] Link update

### ISSUE THREAD

**Issue by obeho** [tycrek/degoogle#397]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Alternative name

Etar in [Calender](https://github.com/tycrek/degoogle#calendar-1)

### Error

The Github page links to a [fork](https://github.com/xsoh/Etar-Calendar) which is unmaintained, instead of the [original](https://github.com/Etar-Group/Etar-Calendar), which is still active.

### Proposed changes

Replace `https://github.com/xsoh/Etar-Calendar` with `https://github.com/Etar-Group/Etar-Calendar`

### Additional details

`None`

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by tycrek** [comment]
Thanks :)
