### ISSUE TITLE
[REMOVE] Blokada

### ISSUE THREAD

**Issue by obeho** [tycrek/degoogle#398]
| Checklist |   |
| --------- | - |
| **I have read the guidelines in [CONTRIBUTING.md]** | yes |
| Include my name in [CONTRIBUTORS.md]                | no |
| I am affiliated with this alternative               | no |

### Alternative name

Blokada in [Other](https://github.com/tycrek/degoogle#other)

### Reason

The app has Anti-Features according to its F-Droid [page](https://f-droid.org/en/packages/org.blokada.alarm/).

![Tracking_Piw0lsEr27GhyCEd_LUODn8QjpyeM7ZhLUo5JuCAkOM=](https://user-images.githubusercontent.com/71698631/129439821-ee0727ca-5547-41a9-8565-a6f5fdbad1c9.jpg) "This app tracks and reports your activity"

and "This app promotes non-free network services"

Sad to see it being recommended by privacy [experts](https://github.com/tycrek/degoogle/issues/102), even after a troublesome public [discussion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8536).

There are 3 more apps in this _Other_ category which are clean. Is it still necessary to include this?

[CONTRIBUTING.md]: ../blob/master/CONTRIBUTING.md
[CONTRIBUTORS.md]: ../blob/master/CONTRIBUTORS.md

**Comment by danarel** [comment]
Based on this, I think this issue should remain open, but I don't think Blokada should be removed. It does look like they are working with the community to properly address the concerns and there seems to be some drama on this page with skews what is really going on. I think removing them might be a rush to judgment, but they certainly seem to have some work to do.

**Comment by obeho** [comment]
The gitlab thread was opened 6 months ago to which they responded with [this](https://community.blokada.org/t/regarding-recent-f-droid-situation/13306), in which they pledge to _address the concerns raised_ in the then upcoming v5.12. It is v5.16 now 4 months later, with no Merge request from them to remove the AntiFeatures markings. They even put up a notice at the top of the app's F-droid [page](https://f-droid.org/en/packages/org.blokada.fem.fdroid/):

> Notice: For background on the current AntiFeatures, please see https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8536

Based on this, it is safe to assume nothing will change. But hey, I'm sure Blokada is being the victim of cancel culture here and let's wait for _objective_ developers to go through the app's code and tell us whether it's unsafe or not. Do we know anybody of sorts? I do, they start with an F and end with Droid. I wonder what their take was.

**Comment by ignoramous** [comment]
> It does look like they are working with the community to properly address the concerns

No, they haven't worked with the community on this at all. Ask F-Droid volunteers about how all of this went down precisely because they didn't.

> there seems to be some drama on this page with skews what is really going on.

That makes you think why is there a drama in the first place, and who benefits from it? Blokada was informed privately about those issues 90 days before I took it up with F-Droid. The only reason they made whatever little changes they did was to keep their privacy rating on [Miriam Ruhenstroth's Mobilscicher website](https://archive.md/tJXGL) in tact and successfully make the other issues seem like a marketing gimmick / FUD.

> I think removing them might be a rush to judgment, but they certainly seem to have some work to do.

Blokada Cloud is what [they're asking folks using their apps to move towards now](https://archive.md/ae6j0), and that's squarely hosted on Google infrastructure. As is the user-registration endpoint `app.blokada.org`. That's *re-googling*. 

```zsh
➜ dig @9.9.9.9 +short cloud.blokada.org
34.117.212.222

➜  whois 34.117.212.222
NetRange:       34.64.0.0 - 34.127.255.255
CIDR:           34.64.0.0/10
NetName:        GOOGL-2
NetHandle:      NET-34-64-0-0-1
Parent:         NET34 (NET-34-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       
Organization:   Google LLC (GOOGL-2)
RegDate:        2018-09-28
Updated:        2018-09-28
Ref:            https://rdap.arin.net/registry/ip/34.64.0.0
```

**Comment by tycrek** [comment]
Sad to see that in October 2023, they're using the **exact same** IP on Google Cloud:

```bash
$ dig +short cloud.blokada.org                                                                                          
34.117.212.222

$ whois 34.117.212.222                                                                                                  
NetRange:       34.64.0.0 - 34.127.255.255
CIDR:           34.64.0.0/10
NetName:        GOOGL-2
NetHandle:      NET-34-64-0-0-1
Parent:         NET34 (NET-34-0-0-0-0)
NetType:        Direct Allocation
OriginAS:
Organization:   Google LLC (GOOGL-2)
RegDate:        2018-09-28
Updated:        2018-09-28
Ref:            https://rdap.arin.net/registry/ip/34.64.0.0
Comment:        *** The IP addresses under this Org-ID are in use by Google Cloud customers ***
```

I'll be removing this soon.
