### ISSUE TITLE
Remove Anonymize.com Email and US.TV

### ISSUE THREAD

**Issue by seanking2919** [tycrek/degoogle#407]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)

### Alternative name

Anonymize.com Email and US.TV

### Reason

Their owner Epik.com has proven to not be as secure and privacy-friendly following the recent major [data breach](https://arstechnica.com/information-technology/2021/09/anonymous-leaks-gigabytes-of-data-from-epik-web-host-of-gab-and-parler/), which included even [data on numerous non-Epik customers](https://twitter.com/troyhunt/status/1439705567400894464?s=20).

**Comment by danarel** [comment]
Seconded. Also, should be a habit not to list anything associated with Epik or those working w// them.

**Comment by tycrek** [comment]
I agree. Will be removed.
