### ISSUE TITLE
[FIX] Mention that Qwant is only available in ~30 countries

### ISSUE THREAD

**Issue by Sush-ruta** [tycrek/degoogle#408]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

Qwant

### Error

In the entry of Qwant, nothing is mentioned about it being available in only a handful of countries (around 30 or so). So most people who try it out will be greeted with a "Service unavailable" page.

### Proposed changes

Please mention the necessary information, as it might be useful to people who reside in countries where Qwant is not available.

### Additional details

Qwant was available in almost all the countries, but in Dec 2020, they restricted their service ([source](https://twitter.com/QwantCom/status/1339149434572206080)) to only 30 or so countries ([source](https://twitter.com/QwantCom/status/1339149436287668225)).

Although which countries are among those 30 are unknown, but [this article](https://tekdeeps.com/qwant-closes-access-to-its-search-engine-in-certain-countries/) has a rudimentary list.

P.S.: Even though the previously mentioned article says that Qwant is available in India, I am also seeing a "Sevice unavailable" page on visiting www.qwant.com which reads ``Unfortunately we are not yet available in your country.`` I guess it is a new update.

**Comment by tycrek** [comment]
Thanks for mentioning this. I'll leave a note directing users back to this Issue for more information.
