### ISSUE TITLE
[NEW] Mull

### ISSUE THREAD

**Issue by SkewedZeppelin** [tycrek/degoogle#411]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [X] I am affiliated with this alternative

### Alternative name

Mull

### Section

Mobile applications

### Description

Mull is a Firefox for Android fork compiled from source, with proprietary blobs removed, and many security/privacy changes made using an altered https://github.com/arkenfox/user.js

### Reason for adding

It provides features that the currently listed ones do not.

### URL

https://divestos.org/index.php?page=our_apps#mull

### Repository

https://gitlab.com/divested-mobile/mull-fenix

### F-Droid ID

https://f-droid.org/en/packages/us.spotco.fennec_dos/

### Other Links

https://github.com/divested-mobile/mull-fenix

### Is this alternative hosted in a country that performs surveillance?

- [X] 5 Eyes
- [ ] 9 Eyes
- [ ] 14 Eyes

### Is there a cost to use this alternative?

Free

### Additional Details

Mull is my project and has existed since 2017: https://divestos.org/misc/ffa-dates.txt

Originally was Fennec based and started as builds of my patchset I upstreamed here https://bugzilla.mozilla.org/show_bug.cgi?id=1419581 in 2017.

**Comment by StephenBrown2** [comment]
Whoops, looks like you missed the 5 eyes @tycrek ... The checkmark is grey to me so maybe a bit hard to see.

**Comment by tycrek** [comment]
> 
> 
> Whoops, looks like you missed the 5 eyes @tycrek ... The checkmark is grey to me so maybe a bit hard to see.

That was intentional as it's an app and it doesn't appear to contact the maintainers servers in any way (@SkewedZeppelin can confirm if that's not the case), but I can add it if you feel there's good reason to include it.
