### ISSUE TITLE
[REMOVE] Vivaldi

### ISSUE THREAD

**Issue by BobIsMyManager** [tycrek/degoogle#412]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

Vivladi

### Reason

Vivaldi is proprietary software, check their [blog post](https://vivaldi.com/blog/technology/why-isnt-vivaldi-browser-open-source/) about why they are **not** open source.

**Comment by LordDraagonLive** [comment]
Is not being an open-source project a good reason to remove this project. This project seems quite promising.

**Comment by BobIsMyManager** [comment]
> Is not being an open-source project a good reason to remove this project
Seeing as there is no note that vivaldi isnt open source like other closed sourced applications on this list, it could be entirely possible that tycrek was unaware that this project is closed source as emby was removed afyer he found out it was closed source.

**Comment by danarel** [comment]
While it's not open source, the source code is available to download and review. 

Some of the look and feel of the project is proprietary, and therefore not open to be used and or copied. 

It's more secure and trustworthy than most other Chrome alternatives and much easier for the user to install and use than UnGoogled Chromium.

I would recommend leaving Vivaldi as you're 100% welcome to check the code. You're just not able to contribute changes directly.

**Comment by BobIsMyManager** [comment]
While that is true, i feel like it is unesserary to have a proprietary alternative like vivaldi for chrome as there are so many other good free and open source alternatives that are still user friendly like firefox, brave and ungoogled chromium.

**Comment by danarel** [comment]
I agree Firefox is a fantastic alternative, but in my professional experience we deal with a lot of people who will demand Chrome based. ungoogled just isn't an ease of use and there is a reason many privacy sites don't recommend it. 

Worse is Brave. I don't consider them a privacy browser one bit. When I was a PrivacyTools (now PrivacyGuide) team member, we got asked all the time to list Brave and this is their official answer:

> Despite being widely touted as a privacy-friendly Chromium browser, we have a number of concerns with Brave’s business practices and future business model that prevents us from recommending them. The Brave team has publicly stated they do not want to be associated with privacy-focused groups like PrivacyTools (PrivacyTools PR #657), which causes us to believe the Brave team does not wish to be under too much scrutiny from the privacy community as they continue to develop their product.

So Given the limited, user friendly options in the Chrome world, I think Vivaldi gives everyone the best alternative.

**Comment by BobIsMyManager** [comment]
If Vivaldi is not removed, at least add a note saying that vivaldi is proprietary software

**Comment by danarel** [comment]
Seems unnecessary. The slisting doesn't claim to be open-source, and other products that are not open source on the site are not listed otherwise. DuckDuckGo, Startpage, MailFence, Piwik, and others.  

Maybe I am alone here but I have not felt this site demands open source to be private, but is listing privacy focused alternative to Google products. While open source is a great goal, 99% of the target audience won't understand how to check code, contribute, etc. Rather they rely on professionals to assess and make their recommendations. 

Making a specific "this product is not open source" would give users a reason to think they should be weary of the product because of that and there is no evidence to support that to be the case.

**Comment by BobIsMyManager** [comment]
Ok you guys convinced me, ill go ahead and close this issue now
