### ISSUE TITLE
[REMOVE] Brave Search

### ISSUE THREAD

**Issue by danarel** [tycrek/degoogle#415]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

Brave Search

### Reason

Brave Search is not a private search engine and is yet another advertising venture by Brave/BAT. 

1. Brave uses Amazon Cloudfront as their CDN, meaning all traffic passes through Amazon servers.

2. Brave makes its money selling ads via its own ad network Brave Ads. Brave Ads do have access to your IP address to serve ads to you locally, though Brave says they are not stored. Brave used Google as their results fall-back in what they call “fallback mixing”.

The issue with "fallback" mixiing is that Brave does not state or demonstrate anywhere (unlike Startpage for example),  that they have a deal with Google to provide secure, anonymous results.

3. They access your IP address upon your visit to determine your location and better serve you ads. While they claim to not store IP addresses, unlike DDG and Startpage, they do read your full IP address which is not private. 

Based on these things, and Brave Browser's shady history, I don't think recommending this search engine is wise. It's also in beta and I don't think near ready for prime time. But the fact they use Google as a fallback and have your IP address demonstrates to me that they are not taking privacy seriously.

**Comment by namelessperson0** [comment]
Brave search supports Tor. 
So, IP tracking is not an issue for those using Tor or an VPN.
In contrast, Google blacklists Tor IP's.

**Comment by namelessperson0** [comment]
> The issue with "fallback" mixiing is that Brave does not state or demonstrate anywhere (unlike Startpage for example), that they have a deal with Google to provide secure, anonymous results.

Brave search is obviously stating that they use fallback mixing with Google services. Check https://search.brave.com/help/google-fallback

Also check side panel in https://search.brave.com/search As of now, Brave search provides 93% of results in own index and rest is from fallback. DuckDuckGo is not transparent on how much they fallback.
