### ISSUE TITLE
DuckDuckGo

### ISSUE THREAD

**Issue by Lightning5trike** [tycrek/degoogle#419]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

DuckDuckGo

### Section

Browser extensions, Desktop applications, Mobile applications

### Description

The browser for mobile comes equipped with a search engine, tracker blocker, encryption enforcer, and more. can also be used as a private search engine. As an extension works for all major browsers.

### Reason for adding

because it allows private searching, blocks tracking and can be used as multiple things (e.g. extension or search engine).

### URL

https://duckduckgo.com/?va=b&t=hc

### Is this alternative hosted in a country that performs surveillance?

- [ ] 5 Eyes
- [ ] 9 Eyes
- [X] 14 Eyes

**Comment by freddy-m** [comment]
This is already listed several times over. cc @tycrek

**Comment by tycrek** [comment]
It is indeed.
