### ISSUE TITLE
[REMOVE] photoprism

### ISSUE THREAD

**Issue by thewhitegrizzli** [tycrek/degoogle#422]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

photoprism

### Reason

site is down

**Comment by StephenBrown2** [comment]
The site appears to be up for me: https://isup.me/photoprism.app
Also, since it's (also) a self-hosted software. the repository is still available and perfectly usable.

However, I see that the website linked on the page is not the current one (`.pro` instead of `.app`). That should be updated.
