### ISSUE TITLE
[NEW] Port Authority

### ISSUE THREAD

**Issue by ACK-J** [tycrek/degoogle#425]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [X] I am affiliated with this alternative

### Alternative name

Port Authority

### Section

Browser extensions

### Description

Port Authority blocks websites from using javascript to port scan your computer/internal-network and also dynamically blocks all LexisNexis endpoints from running their invasive data collection scripts. The addon is FOSS and easily auditable with only ~250 lines of main functionality. 

### Reason for adding

Its not widely understood how invasive javascript port scanning is. Javascript has the ability to port scan your entire internal network behind a NAT, this is the only Addon built specifically to stop this type of attack, additionally lexis nexis data collection scripts will be blocked.

### URL

https://www.g666gle.me/Port-Authority/

### Repository

https://github.com/ACK-J/Port_Authority

### Is this alternative hosted in a country that performs surveillance?

- [ ] 5 Eyes
- [ ] 9 Eyes
- [ ] 14 Eyes

### Is there a cost to use this alternative?

Free

**Comment by tycrek** [comment]
Looks good, will add
