### ISSUE TITLE
[NEW] ProtonAOSP

### ISSUE THREAD

**Issue by Kydaix** [tycrek/degoogle#430]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

ProtonAOSP

### Section

Operating systems

### Description

ProtonAOSP is a "Minimal Android fork for design and performance" for Pixel devices, which is based on Android 11 & 12.
This ROM can be used with [MicroG](https://microg.org/) and has many interesting features.

### Reason for adding

This ROM seems to be a very good alternative for any Pixel owner, and appears to give a similar experience to stock Android.

### URL

https://protonaosp.kdrag0n.dev/

### Repository

https://github.com/ProtonAOSP

### Is this alternative hosted in a country that performs surveillance?

- [ ] 5 Eyes
- [ ] 9 Eyes
- [ ] 14 Eyes

### Is there a cost to use this alternative?

Free

**Comment by dngray** [comment]
Do not add this, they charge for security updates https://github.com/orgs/privacyguides/discussions/455#discussioncomment-1792431 so that's not free at all.
