### ISSUE TITLE
[NEW] Photoview - self-hosted photo albums

### ISSUE THREAD

**Issue by mniehe** [tycrek/degoogle#442]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [x] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

Photoview

### Section

Web-based products

### Description

Self-hosted and open-source Personal Photo Management with options for face grouping, albums, sharing, automatic thumbnail generation, and map pins.

### URL

https://photoview.github.io/

### Repository

https://github.com/photoview/photoview

### Is this alternative hosted in a country that performs surveillance?

- [ ] 5 Eyes
- [ ] 9 Eyes
- [ ] 14 Eyes

### Is there a cost to use this alternative?

Free

### Please indicate if self-hosting is possible, not possible, or the only option

Only self-hosted

**Comment by tycrek** [comment]
Resolved in #443
