### ISSUE TITLE
[NEW] Lomorage - self-hosted cross-platform photo backup/management solution

### ISSUE THREAD

**Issue by dwebfan** [tycrek/degoogle#444]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [X] I am affiliated with this alternative

### Alternative name

Lomorage

### Section

Web-based products, Desktop applications, Mobile applications

### Description

Lomorage enables people to backup photos / videos from any devices to their own self-hosted server, and intelligently manages these personal assets via AI. Run the Lomorage server at your home, download mobile client to save the memories, and enjoy the moments.

### URL

https://lomorage.com/

### Repository

https://github.com/lomorage/homepage

### Is this alternative hosted in a country that performs surveillance?

- [ ] 5 Eyes
- [ ] 9 Eyes
- [ ] 14 Eyes

### Is there a cost to use this alternative?

Free

### Please indicate if self-hosting is possible, not possible, or the only option

Only self-hosted

**Comment by tycrek** [comment]
Resolved in #448
