### ISSUE TITLE
mailbox.org on mobile devices

### ISSUE THREAD

**Issue by avasts** [tycrek/degoogle#45]
When you sign up for a mailbox.org account, it will give the IMAP settings to allow adding to any mail app. I've successfully added a mailbox.org account on iOS and Android devices using the IMAP settings provided. 

It may need to be noted that iOS devices require a profile to be downloaded and installed for calendar and tasks to work properly, but I do not recall Android requiring any additional downloads in order to add the IMAP info.

**Comment by tycrek** [comment]
Thanks for the info, I will update Mailbox.org in the mobile section.
