### ISSUE TITLE
[REMOVE] YouTube Vanced

### ISSUE THREAD

**Issue by Mennaruuk** [tycrek/degoogle#452]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

YouTube Vanced

### Reason

[Google has sent a cease-and-desist letter to the maintainers of YouTube Vanced, pressuring them to shut down the five-year-old app.](https://www.androidauthority.com/youtube-vanced-discontinued-3132147)

**Comment by tycrek** [comment]
Alternatively can be replaced with [ReVanced](https://revanced.app/) ([GitHub org](https://github.com/revanced))
