### ISSUE TITLE
[REMOVE] CTemplar shutting down

### ISSUE THREAD

**Issue by qskousen** [tycrek/degoogle#458]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

CTemplar

### Reason

CTemplar is shutting down. https://ctemplar.com/ctemplar-is-shutting-down/

**Comment by tycrek** [comment]
Resolved in #480
