### ISSUE TITLE
[REMOVE] HTTPS Everywhere

### ISSUE THREAD

**Issue by ghost** [tycrek/degoogle#459]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

HTTPS Everywhere

### Reason

HTTPS Everywhere is [going to be deprecated](https://www.eff.org/nb/deeplinks/2021/09/https-actually-everywhere) after 2022. Firefox and Chrome already support HTTPS-Only modes.

**Comment by Technetium1** [comment]
This should definitely not yet be removed until it's actually inoperable. There are no other extensions supporting mixed content rulesets! This allows many sites to be force do use HTTPS except on known broken domains, [even some of Google's own domains](https://atlas.eff.org/domains/googleusercontent.com.html) need to have these rulesets to maintain full functionality.

**Comment by dngray** [comment]
What happens on browsers with https-only mode is they will display a warning saying "are you sure you want to go to the http site", click here to bypass.

That way they avoid enumeration of badness by simply not having  rule set, so yes, https-everywhere definitely should be removed as it has been superseded by better options. Also it's unmaintained upstream.

**Comment by Technetium1** [comment]
That warning does not work for mixed content on separate domains since the browser doesn't modify CSP in the same way the extension does (that was the reason to the best of my memory). The extension will be sunset 2023, but in the meantime it's still being maintained as are the rulesets, so why remove it? At least replace it with how to turn on HTTPS only mode https://www.eff.org/https-everywhere/set-https-default-your-browser.

**Comment by tycrek** [comment]
Reopening for now until I check the status of HTTPS Everywhere

**Comment by tycrek** [comment]
HTTPS Everywhere is to be removed.

- [EFF Blog post (2021)](https://www.eff.org/deeplinks/2021/09/https-actually-everywhere)
- [More info & extension downloads](https://www.eff.org/https-everywhere)
