### ISSUE TITLE
[REMOVE] ClearURLs

### ISSUE THREAD

**Issue by ghost** [tycrek/degoogle#461]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

ClearURLs

### Reason

ClearURLs is redundant with uBlock Origin's `removeparam` feature. Enable the `AdGuard URL Tracking Protection` in uBlock Origin and you'll get the same functionality.

**Comment by Technetium1** [comment]
I don't think ClearURLs should be removed.
