### ISSUE TITLE
[REMOVE] TrackMeNot

### ISSUE THREAD

**Issue by ghost** [tycrek/degoogle#462]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

TrackMeNot

### Reason

TrackMeNot is not [currently being maintained](https://github.com/vtoubiana/TrackMeNot) and hasn't had an update in over 3 years.

**Comment by Technetium1** [comment]
@tycrek might want to expedite removal because of this. https://github.com/vtoubiana/TrackMeNot/issues/139
