### ISSUE TITLE
[REMOVE] minerBlock

### ISSUE THREAD

**Issue by ghost** [tycrek/degoogle#463]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [ ] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

minerBlock

### Reason

minerBlock hasn't [been updated in over 3 years](https://addons.mozilla.org/en-US/firefox/addon/minerblock-origin/), it is abandonware.

**Comment by Technetium1** [comment]
Do all of these domains show up in other block lists? https://github.com/xd4rker/MinerBlock/blob/master/assets/filters.txt

**Comment by mfwmyfacewhen** [comment]
Idk but can't you just add their blocklist to UBO?

**Comment by Technetium1** [comment]
Is that all valid adblock syntax? :thinking:
