### ISSUE TITLE
[FIX] Atom

### ISSUE THREAD

**Issue by osfanbuff63** [tycrek/degoogle#478]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

GitHub Atom

### Error

Atom is [being sunsetted](https://github.blog/2022-06-08-sunsetting-atom/).

### Proposed changes

There should either be:
- A note that Atom is being sunsetted
- Removed from the list entirely

### Additional details

It isn't fully sunsetted until December, so this might not be too urgent? Up to you though.

**Comment by Sertonix** [comment]
Atom is continued by the community under the name [Pulsar](https://pulsar-edit.dev/). So replacing it would be better.
