### ISSUE TITLE
[REMOVE] I don't care about cookies

### ISSUE THREAD

**Issue by ilar** [tycrek/degoogle#482]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

I don't care about cookies

### Reason

This extension has been aquired by Avast, which has had a historically poor track record regarding user privacy.

https://www.androidpolice.com/i-dont-care-about-cookies-acquired-by-avast/

**Comment by osfanbuff63** [comment]
There's a community-maintained fork that should be recommended instead: https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/

**Comment by Splarkszter** [comment]
No way this hasn't been done yet. Avast is a huge privacy invasor.

**Comment by freddy-m** [comment]
FWIW, almost all of the extensions listed now ought to be removed. All you realistically need is uBlock Origin and a password manager - everything else just makes you stick out.
