### ISSUE TITLE
[REMOVE] Android Messages - Signal

### ISSUE THREAD

**Issue by hyacin75** [tycrek/degoogle#499]
### Checklist

- [X] **I have read the guidelines in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md)**
- [X] Include my name in [CONTRIBUTORS.md](../blob/master/CONTRIBUTORS.md)
- [ ] I am affiliated with this alternative

### Alternative name

Signal (Android Messages section)

### Reason

As per this guide I installed Signal to handle my SMS but was sad to see as soon as I made it my default SMS app, that I got a pop-up that said "SMS support is going away soon".

It is slated for August 31st, and they're trying to transition people off and have them export their SMS messages now.

Probably best to remove it from the list now as no one should really be onboarding to it at this time.

**Comment by tycrek** [comment]
Won't be removing Signal at this time; see #523 for more info (will be modifying the parent section instead).
