### ISSUE TITLE
Add the Framasoft alternatives

### ISSUE THREAD

**Issue by NicolasPA** [tycrek/degoogle#5]
Framasoft is a French non-profit that does amazing work for free software and digital freedom.
https://framasoft.org/en/

They perfectly fit this project, to "de-google-ify internet" has been one of their goals for a while.
You can read their philosophy about it here: https://degooglisons-internet.org/en/

Here's the list of web services they provide: https://degooglisons-internet.org/en/list/

Here's their own list of alternatives they suggest in general: https://degooglisons-internet.org/en/alternatives/

**Comment by tycrek** [comment]
I'll add this near the top of useful links because of the amount of stuff they provide. Great recommendation.
