### ISSUE TITLE
Google Docs/Slides/Sheets alternative

### ISSUE THREAD

**Issue by arguiot** [tycrek/degoogle#52]
One very popular alternative to these services is of course iCloud.com which offers collaboration & synchronisation with Apple devices (note that an Apple device is not required to use iCloud.com)

**Comment by tycrek** [comment]
I'm not against recommending Apple, but I would prefer a few articles to explain in detail why they are privacy focused. Unfortunately I cannot just take Apple's own word for it.

Like I said, as long as you can find good articles or info recommending their privacy, I will consider adding iCloud.

**Comment by arguiot** [comment]
Of course, I understand.

Here are a quick list of facts/articles about Apple & privacy
- First of all, they have an entire [page](https://www.apple.com/privacy/) on their website about it.
- they refused to help the FBI by not giving them access to an attacker’s data
- They have an entire advertisement campaign on privacy
- DuckDuckGo (which is on your list) uses Apple Maps by default for privacy
- https://arstechnica.com/gadgets/2012/03/how-safe-is-icloud-data-ars-investigates/
- Apple never had any issues with iCloud’s privacy (except the celebrity photos which was based on phishing, so not their fault)

**Comment by tycrek** [comment]
Looks good. What services would you recommend iCloud for? I know for sure they do storage, but can you access their other apps with a browser on a non-mac system?

**Comment by tycrek** [comment]
[This thread](https://old.reddit.com/r/privacy/comments/eqg5gc/apple_complies_with_90_requests_from_government/?ref=share&ref_source=link) came up on r/privacy. Thoughts?

**Comment by taraletti** [comment]
To me, this is the best alternative https://arcaneoffice.com

**Comment by kylesf** [comment]
I use https://github.com/ReinerNippes/nextcloud_on_docker with [Colloborra integrated](https://nextcloud.com/collaboraonline/). Hosted on a VPS.

**Comment by k3tan172** [comment]
Now that Nextcloud 18 has OnlyOffice alongside Community Document Server integrated, you can self host your shared documents/slides/spreadsheets.

**Comment by tycrek** [comment]
@taraletti @kylesf @k3tan172 Please open a new Issue for each of your services, it is easier to track and discuss individual services if they have their own issue.

**Comment by tycrek** [comment]
> [This thread](https://old.reddit.com/r/privacy/comments/eqg5gc/apple_complies_with_90_requests_from_government/?ref=share&ref_source=link) came up on r/privacy. Thoughts?

No response to this, closing until there is adequate information to re-open.
