### ISSUE TITLE
Don't recommend Zoho

### ISSUE THREAD

**Issue by ribtoks** [tycrek/degoogle#53]
Hey, why do you even recommend Zoho? It's another proprietary cloud based in India. There were [controversial reports](https://news.ycombinator.com/item?id=18056723) of their staff reading your emails. 

They offer you 5GB for free with custom domain which is almost not different from Gmail offering (5GB for emails is quite a lot) and their web apps are quite good. Why would anybody offer you good software and cloud space absolutely free? You will have same story as with Gmail, Outlook etc.

**Comment by tycrek** [comment]
You make good points. I appreciate the link. I will update it to remove Zoho.

**Comment by kevquirk** [comment]
I feel like removing Zoho as a recommendation based on a single comment that hasn’t been validated is a little naive. Especially since someone claiming to work for Zoho has responded to said comment, with links to backup their claims.

**Comment by ribtoks** [comment]
@kevquirk that is true from some point of view, but Zoho is a big corporation offering you lots of services and cloud space for free. It is not better than Google and not a good alternative.

Also actual responses from Zoho guys in Hacker News thread are just words and those links didn't actually prove anything. You will never know how they treat your data.

**Comment by tycrek** [comment]
@ribtoks @kevquirk I'm just at work right now, but at some point I'll try to find time to read through Zoho's privacy policy (if either of you or anyone else wants to instead that would be great, but not necessary). I'm not completely decided on whether it should be in the guide or not so for now I will reopen this issue. 

As an aside, it is a bit concerning for me when a company provides such a variety of services at no cost. I'll know for sure after reading their policy, but in my experience companies that do this make money from selling user data. Even if they do not sell data, this guides primary focus is privacy focused services. If there is good evidence that Zoho is not optimal for privacy, it will not be added.

**Comment by GreyLivesMatter** [comment]
To be fair, Zoho has a pretty transparent disclaimer stating their business mission is that if they give away services for free, that one may consider using their corporate packages for business reasons so just because it isn't out there as 100% free and open-source, I don't see why it's an issue.

Github offers lots of services for free too, but they still have a premium option and various abilities to push financial products -- especially with MS at the helm.

**Comment by kevquirk** [comment]
@tycrek Zoho's privacy policy is pretty transparent. The summary says the following:

> Our privacy commitment: Zoho has never sold your information to someone else for advertising, or made money by showing you other people's ads, and we never will. This has been our approach for almost 20 years, and we remain committed to it. This policy tells you what information we do collect from you, what we do with it, who can access it, and what you can do about it.

Link to full policy: https://www.zoho.com/privacy.html

@ribtoks correct, the comment from Zoho's team member are just words, but so are the original comment. What's to stop me claiming I know someone who works from Proton or Tutanota, or mailbox.org and say that they have access to their customers emails? Would these services be removed from such a list on this based on my say so alone? I don't think it should be, before actively not recommending a service, these claims should be verified, I feel.

Why would the support people be asking for the complete emails so they can see the headers, if they have access to users' mail?

Yes, Zoho offer a free service with 5GB storage. But they do this so they can up-sell to their paid offerings. There is no advertising anywhere, even in their free tiers, and their privacy policy is pretty transparent.

Their business model is to up-sell, not to sell their users' privacy, like Google. Full disclosure - I've been a happy user (paid) of Zoho for a few years and I'm very happy with their service. I class myself as a privacy advocate, and have no problem recommending them.

Obviously, if the claims the person on HN made get proven to be true, I would immediately stop using their service. However, I see no data to the contrary and my own dealings with Zoho support have always been relatively positive. I was even refused access to an old account where I had lost the 2FA keys. So to me, they take privacy and security seriously.

Just my 2p worth. :)

**Comment by tycrek** [comment]
This is a great discussion. I feel like we should revert [this commit](https://github.com/tycrek/degoogle/commit/e060eaf16428dd086251b61877174755e761d811) in this case. I'm open to anyone's thoughts.

(If someone more experienced with Git knows an easy way to revert that specific commit, I'd love to hear it. Or a Pull Request works too!)

**Comment by vijayarahuraman** [comment]
> This is a great discussion. I feel like we should revert [this commit](https://github.com/tycrek/degoogle/commit/e060eaf16428dd086251b61877174755e761d811) in this case. I'm open to anyone's thoughts.
> 
> (If someone more experienced with Git knows an easy way to revert that specific commit, I'd love to hear it. Or a Pull Request works too!)

As suggested [pull request](https://github.com/tycrek/degoogle/pull/89) has been initiated. Kindly do the favor.
