### ISSUE TITLE
[OTHER] State that FitBit should not be used

### ISSUE THREAD

**Issue by ribtoks** [tycrek/degoogle#56]
You state that people should not use Waze because it belongs to Google.

Then you should also state that people should not use FitBit. Alternatives to be added.

**Comment by tycrek** [comment]
I agree. Where should this be noted? I'm thinking either a note under Wear OS or just add a new section for FitBit under Hardware.

**Comment by ribtoks** [comment]
In my opinion Hardware section fits better, thanks.
