### ISSUE TITLE
Sulincix android project  template

### ISSUE THREAD

**Issue by paledega** [tycrek/degoogle#58]
We can use android studio alternative.
https://gitlab.com/sulincix/project-creator
buiding android apps without ide. 
Makefile template

**Comment by paledega** [comment]
more info : t.me/sulincix

**Comment by tycrek** [comment]
Could you please provide a bit more info on what this is exactly?

**Comment by tycrek** [comment]
> Could you please provide a bit more info on what this is exactly?

No response.
