### ISSUE TITLE
[NEW] Docs alternative: LyX

### ISSUE THREAD

**Issue by Glitchy-Tozier** [tycrek/degoogle#61]
**Service name**: *LyX (and LaTeX in general)*

**Service URL**: *https://www.lyx.org/*

**5/9/14 eyes?**: unknown

**Description**: *It's an open-source (and offline) document processor. It's different than Docs or Word but amazing, once you get used to it.*

**Comment by tycrek** [comment]
Looks interesting, I'll add it in. Thanks
