### ISSUE TITLE
[NEW] Gboard alternative: OpenBoard

### ISSUE THREAD

**Issue by Glitchy-Tozier** [tycrek/degoogle#62]
**Gboard replacement**: *OpenBoard*

**Service URL**: *https://github.com/dslul/openboard*

**5/9/14 eyes?**: unknown

**Description**: *New 100% FOSS keyboard, based on AOSP. Similar to "Simple Keyboard".*

**Comment by tycrek** [comment]
Thank you, I'll add it in
