### ISSUE TITLE
[NEW] Infinity Search

### ISSUE THREAD

**Issue by InfinitySearch** [tycrek/degoogle#68]
**Service name:** Infinity Search

**Service URL:** [https://infinitysearch.co](https://infinitysearch.co)

**5/9/14 eyes?:** 5 eyes 

**Description:** 
Infinity Search is a privacy metasearch engine that does not log any information about its users. In terms of privacy, it works the same way as DuckDuckGo. It is free to use and is funded by non-tracking advertisements and affiliate links. It is also completely open source at [https://gitlab.com/infinitysearch/infinity-search](https://gitlab.com/infinitysearch/infinity-search).  The privacy policy can be found at [https://infinitysearch.co/privacy](https://infinitysearch.co/privacy).

Infinity Search currently has search capabilities for websites, images, news, videos, and maps. 

One way that it is different from other search websites is that it has a sidebar that makes it easy to search for the same topic on several other sites if you can't initially find what you're searching for.

**Comment by tycrek** [comment]
Looks good, I will read the privacy policy before adding it. As your account appears to be the corporate account, can you tell me if you run your own indexer or if you act as a "proxy" of sorts by displaying results from other search engines?

**Comment by InfinitySearch** [comment]
We do not currently run our own indexer and our results primarily come from the Bing search API and the DuckDuckGo Instant Answers API.

**Comment by InfinitySearch** [comment]
Dear Joshua, 

Did you ever get a chance to look at our privacy policy? Please let us know if you have any more questions about our service.

**Comment by tycrek** [comment]
@InfinitySearch Just got around to it. I'll add it in right away.
