### ISSUE TITLE
[REMOVE] Remove brave browser

### ISSUE THREAD

**Issue by moon-chilled** [tycrek/degoogle#69]
Brave's business model is basically to block websites' native ads and replace them with their own.  This isn't something that should be encouraged.

**Comment by tycrek** [comment]
I agree with you on that point. I'll leave this issue open for now in case anyone has a valid reason to dispute this, but if there is no opposition I'll remove it within the week. (If I forget to just ping me)

**Comment by rchavik** [comment]
I disagree. I think Brave is trying to solve a hard problem and attempting to offer a privacy focused ad-platform. 

It may still have to work out some kinks, but I think it can stay on list.

**Comment by pajamaw** [comment]
Whether or not to remove it from the desktop applications is one thing, but I'd definitely add Brave as an alternative to Google Adsense, as Brave Ads is user-first
(still in beta though)
https://brave.com/brave-ads-waitlist/

**Comment by danarel** [comment]
It’s worth noting that Peter Thiel is one of the major investors in Brave. He’s the founder of Palantir, and sits on the Facebook board of directors. 

Palantir has long advocated for violating data privacy rights and also develops software for ICE in the US. 

YouTuber Tom Scott was not happy to learn that Brave was collecting funds on his behalf, and then keeping them because Scott wasn’t signed up as part of their creator platform. While brave has done some work to improve this, they started off with a shady business model and honestly, Brave isn’t  much more than adware mean to sell their cryptocurrency. 

How anyone trusts brave is beyond me.

**Comment by tycrek** [comment]
@danarel for sake of discussion, would you mind providing links for your points? I remember hearing about Tom Scott and Brave but am far too tired to look it up right now as it's nearly 1AM for me. Otherwise I can look up links later on.

**Comment by tycrek** [comment]
### Peter Thiel investing

- [Investors bolster Brave's plan to rid web of nasty ads - CNET](https://www.cnet.com/news/new-funds-help-browser-maker-brave-try-ridding-the-web-of-nasty-ads/)
- [Aral Balkan via Twitter](https://twitter.com/aral/status/1119575612203704320?lang=en) (link within the tweet is dead, see [backup on Archive.org](https://web.archive.org/web/20190512112104/https://mastodon.at/@switchingsocial/101941233246966746))
- [Peter Thiel - Wikipedia (Facebook section)](https://en.wikipedia.org/wiki/Peter_Thiel#Facebook)

### Palantir

- [Palantir Technologies - Wikipedia (Entire section dedicated to numerous controversies)](https://en.wikipedia.org/wiki/Palantir_Technologies#Controversies)

### Tom Scott & Brave

- [Famous Youtuber Tom Scott Frustrated With Brave - Altcoin Buzz](https://www.altcoinbuzz.io/cryptocurrency-news/spotlight/famous-youtuber-tom-scott-frustrated-with-brave/)
- [Prominent YouTuber Claims Brave’s BAT Payments System Violates GDPR - CCN](https://www.ccn.com/prominent-youtuber-claims-braves-bat-payments-system-violates-gdpr/)
- [@tomscott on Twitter (Archive.org link as original tweet has been removed)](https://web.archive.org/web/20190606100032/https://twitter.com/tomscott/status/1076160882873380870)

### Numerous issues on the [privacytools.io GitHub repo](https://github.com/privacytoolsIO/privacytools.io) about Brave

- [Brave should be listed again #1820](https://github.com/privacytoolsIO/privacytools.io/issues/1820)
- [Software Suggestion | Brave Browser #1806](https://github.com/privacytoolsIO/privacytools.io/issues/1806)
- [Software Suggestion | Brave Browser #1541](https://github.com/privacytoolsIO/privacytools.io/issues/1541)
- [Website Issue | Explicitly mention that using Brave is highly discouraged #1332](https://github.com/privacytoolsIO/privacytools.io/issues/1332)
- [**Remove Brave #1169**](https://github.com/privacytoolsIO/privacytools.io/pull/1169)
- [Software Removal | Brave Browser #758](https://github.com/privacytoolsIO/privacytools.io/issues/758)
- [[Discussion] Remove Brave #657](https://github.com/privacytoolsIO/privacytools.io/pull/657)
- [Software Removal | Brave #649](https://github.com/privacytoolsIO/privacytools.io/issues/649)
- [browser recommendation: Brave #78](https://github.com/privacytoolsIO/privacytools.io/pull/78)

To quote [@dawidpotocki](https://github.com/dawidpotocki), in [this issue](https://github.com/privacytoolsIO/privacytools.io/issues/1332#issuecomment-533773008):

> Nope. We don't need another shitstorm.

### My conclusion

Brave is no doubt a shady company with a history of bad business practices. I would say the majority of people in the privacy/security area do not forgive these kinds of practices easily. Once trust is broken, it's hard to get it back. I'm not here to right an essay, so I'll end with this: **Brave Browser is being removed and will not be added again, to avoid headaches such as all the above** Any issues or PR's to add Brave back will be closed.
