### ISSUE TITLE
[NEW] New alternative: text editor/development tools

### ISSUE THREAD

**Issue by moon-chilled** [tycrek/degoogle#70]
[Vim](https://www.vim.org/), [Emacs](https://www.gnu.org/software/emacs/).  Both are completely opensource; not hosted, no telemetry.

**Comment by tycrek** [comment]
What section would you suggest these be put under? The Android Studio section is primarily for alternatives facilitating (objectively) easy Android development, and I doubt a text editor would be able to do that, but I may be wrong.

**Comment by moon-chilled** [comment]
It says:

> (not specifically for Android development, just in general)

**Comment by tycrek** [comment]
@moon-chilled Forgot about that note, thanks for the reminder.

**Comment by tycrek** [comment]
* Forgot to add that I will put those in the list
