### ISSUE TITLE
[NEW] New alternative to Google Docs/Sheets/Slides

### ISSUE THREAD

**Issue by k3tan172** [tycrek/degoogle#73]
**Service name**: Nextcloud 18 with Community Document Server and OnlyOffice apps installed.

**Service URL**: https://www.nextcloud.com https://www.onlyoffice.com

**5/9/14 eyes?**: yes

**Description**: Nextcloud 18 now has Community Document Server and OnlyOffice apps integrated which allows self hosted instances of docs/sheets/slides. Users are able to edit documents in real time.

**Comment by plutocrat** [comment]
I'd say on the strength of this recent development, you might even consider bumping Nextcloud up to "Gsuite replacement". It does files, email, docs, calendar, video conferencing, contacts, talk, messaging ... and more depending on what plugins  you install.

**Comment by tycrek** [comment]
@plutocrat I'll have to take your word for it but I agree (Nextclouds website nearly crashed my laptop somehow...). These two make a good alternative for G Suite.
