### ISSUE TITLE
[NEW] New alternative to Google Docs/Sheets/Slides

### ISSUE THREAD

**Issue by taraletti** [tycrek/degoogle#76]
**Service name**: *Arcane Office. Blockchain-based private online office suite*

**Service URL**: *https://arcaneoffice.com*

**5/9/14 eyes?**: unknown

**Description**: *Arcane Office is a decentralized office suite with high-security and zero-knowledge on your data. With Arcane Office, you have maximum control on your personal stuff. Full-featured online document and spreadsheet editor. Secure storage to save your photos. All free for personal use. Arcane Office is in beta state, so we don't have a pricing structure yet. But don't worry, there will always be a free version, and we let you know before any changes happen. Arcane Office encrypts all your document and photos and then send them to a hub of your choice. The default storage provider is Gaia by Blockstack. It's decentralized storage that works by hosting data in one or more existing storage systems. Thanks to Blockstack, you have an option to choose your own storage provider if you want. There is no difference in what provider you are using; Arcane Office will encrypt all your data with the highest security standards.Arcane Office operates as a transparent and secure system based on Bitcoin blockchain. It will always encrypt everything using ECIES and AES256 encryption, and only a specific recipient key can decrypt it. Also, the protocol codebase is open-source and hosted on GitHub.*

**Comment by taraletti** [comment]
@tycrek

**Comment by tycrek** [comment]
@taraletti Still getting around to these issues after a bit of a break. Just having lunch then I'll take a look.

**Comment by tycrek** [comment]
Looks interesting. Marks also look like a potential alternative for Google Keep. Added.

**Comment by taraletti** [comment]
indeed, it have some others apps for web browser like black hole and an office suite
