### ISSUE TITLE
[NEW] Hangouts and Drive → Keybase

### ISSUE THREAD

**Issue by notpushkin** [tycrek/degoogle#81]
**Service name**: Keybase

**Service URL**: https://keybase.io/

**5/9/14 eyes?**: 5-eyes (United States)

**Description**: end-to-end encrypted chats, encrypted file storage (250 GB), **doesn't require phone number to sign up** (unlike Signal & co.), open source and free to use (unlike Threema).

My only concern is that they [explicitly ask](https://github.com/keybase/client#warnings) to use their binaries and not compile from source, but AFAIK it doesn't do anything nasty.

**Comment by notpushkin** [comment]
UPD: I see it's already in the list, but only in the mobile apps section. It is in fact perfectly usable as a desktop app, too, so I would add it in the main “services” list as well.

**Comment by taraletti** [comment]
I tried, and it's nice. The android app must have some improves

**Comment by tycrek** [comment]
I like that they also have a Tor link. Looks very user-friendly.
