### ISSUE TITLE
[NEW] Android (Google Service Framework) → microG

### ISSUE THREAD

**Issue by notpushkin** [tycrek/degoogle#83]
**Service name**: microG and LineageOS for microG

**Service URL**: https://microg.org/, https://lineage.microg.org/

**5/9/14 eyes?**: unknown

**Description**: microG a re-implementation of Google’s proprietary Android user space apps and libraries. It allows to use more precise navigation (which is proprietary in standard Android ROMs) and optionally receive push messages (requires connection to Google's servers, but it's the only way so uh; it also supports routing this connection through Tor I guess?).

It's briefly mentioned in Aurora Store entry (as an optional dependency, which isn't true by the way – it doesn't interact with microG at all, see [Do I need Google Play Services to use *Aurora Store*?](https://gitlab.com/AuroraOSS/AuroraStore/-/blob/master/README.md#L77)) but I uess it could get a bit more love <3

**Comment by tycrek** [comment]
Thanks, I'll add this in a new subsection for **Play Services Framework** in the **Android** section
