### ISSUE TITLE
[NEW] Ara

### ISSUE THREAD

**Issue by FultonBrowne** [tycrek/degoogle#93]
**Service name**: ara

**Service URL**: https://github.com/FultonBrowne/Ara-android https://github.com/FultonBrowne/Ara-Server

**5/9/14 eyes?**: unknown

**Description**: Ar is a voice assistant that has some very basic iot capability, full search capability, and expected voice assistant stuff. ara is free and private

**Comment by tycrek** [comment]
Does the Android client require the server to be set up? Also, is it integrated into Android in a way that it can replace Google Assistant when long pressing Home? Looks interesting, I'll add it when I have some more time. 

Side note, can it connect to [Home Assistant](https://home-assistant.io)? I've been looking for a voice assistant on Android to control HA. But that's more for myself rather the guide.

**Comment by FultonBrowne** [comment]
I host a server, but anyone can self host. you can set ara as a default voice assistant in settings and I am planning to add home assistant compatibility, I will set it as a priority. thx for adding it :]

**Comment by tycrek** [comment]
Added Ara.

**Comment by FultonBrowne** [comment]
thanks :]
