### ISSUE TITLE
[NEW] New alternative for Google Forms

### ISSUE THREAD

**Issue by compressstudio** [tycrek/degoogle#95]
**Service name**: *BlockSurvey - Privacy-focused surveys, polls & forms*

**Service URL**: *https://blocksurvey.io*

**5/9/14 eyes?**: no

**Description**: * BlockSurvey enables digital rights(identity and data ownership) to users using Blockstack's blockchain. Users truly own their data with BlockSurvey. All your data collection is protected using your key and only you can access it. You have the key to it. There are no trackers or cookies or fingerprints on the forms of data providers. Yet to charge users. It is free to use.*

**Comment by tycrek** [comment]
Not sure what you mean by "yet to charge users. it is free to use". I could only find [paid plans](https://blocksurvey.io/pricing) on their website. Can you clarify this?

**Comment by compressstudio** [comment]
Hi, it is free to use for now since I don't have payment integrated yet. All features are open to be used. It's in beta. Have this line on the top of pricing page. ("Free for now! Subscription coming soon!") https://blocksurvey.io/pricing

**Comment by woutfeys** [comment]
You sure it's not just something they do for covid19 and then remove afterwards?
