### ISSUE TITLE
[OTHER] Translation to german Language

### ISSUE THREAD

**Issue by arentro** [tycrek/degoogle#96]
Hello,

I translated your collection of tools into German. This might help the Germans who don't speak English or don't speak any English to turn away from Google as well.

If you update something on your site, I will translate it into German. 

I hope you like it!

Stay safe!

repo: [https://github.com/arentro/degoogle_german](https://github.com/arentro/degoogle_german)

**Comment by tycrek** [comment]
This is amazing, thank you so much! [Added to mirrors list](https://github.com/tycrek/degoogle/commit/5f96e6775f5a3159261e1446b86325f412ea8b9c)
